{ pkgs, ... }:

let
  layout = import ../../lib/layout.nix {
    nixosRoot = ../..;
  };
  dotsRoot = layout.dots;
  shellRuntimeManifest = builtins.fromJSON (
    builtins.readFile (layout.installer + "/internal/shellruntime/manifest.json")
  );
  mkOpacityFallback =
    path:
    { vendor, target }:
    ''
      ${path} = (
        if ${path} == null or ${path} == ${toString vendor}
        then ${toString target}
        else ${path}
        end
      )'';
  jqBool = value: if value then "true" else "false";
  mkBoolDefault = path: value: ''
    if ${path} == null
    then ${path} = ${jqBool value}
    else .
    end'';
  mutableSeedHelper = pkgs.writeShellApplication {
    name = "wahrwelt-mutable-seed";
    runtimeInputs = [ pkgs.python3 ];
    text = ''
      exec python3 ${./mutable-seed.py} "$@"
    '';
  };
in
{
  inherit
    dotsRoot
    layout
    mkBoolDefault
    mkOpacityFallback
    mutableSeedHelper
    ;

  hyprRuntimeFiles = shellRuntimeManifest.runtimeFiles;
  inherit (shellRuntimeManifest) hyprScripts end4Scripts;

  forcedSource = source: {
    inherit source;
    force = true;
  };

  mkOpacityDefault =
    trans: path:
    mkOpacityFallback path {
      vendor = trans.vendorShell;
      target = trans.shell;
    };

  stableRuntimeSourceFile = target: {
    force = true;
    text = ''
      source = ${target}
    '';
  };

  stableLuaRuntimeSourceFile = target: {
    force = true;
    text = ''
      -- Generated by Wahrwelt: stable Hyprland Lua runtime entrypoint
      local home = os.getenv("HOME")
      if home == nil then
          error("HOME is not set; cannot locate Wahrwelt Hyprland runtime")
      end

      local config_home = os.getenv("XDG_CONFIG_HOME") or (home .. "/.config")
      local hypr_root = config_home .. "/hypr"
      package.path = hypr_root .. "/?.lua;" .. hypr_root .. "/?/init.lua;" .. package.path
      dofile(${builtins.toJSON target})
    '';
  };

  mutableJsonShellHelpers = ''
    ensure_real_directory() {
      local target="$1"

      $DRY_RUN_CMD "${mutableSeedHelper}/bin/wahrwelt-mutable-seed" \
        ensure-dir "$HOME" "$target"
    }

    seed_directory_if_missing() {
      local target="$1"
      local source="$2"

      $DRY_RUN_CMD "${mutableSeedHelper}/bin/wahrwelt-mutable-seed" \
        seed-tree "$HOME" "$target" "$source"
    }

    seed_if_missing() {
      local target="$1"
      local source="$2"
      local home_replacement="''${3:-}"

      $DRY_RUN_CMD "${mutableSeedHelper}/bin/wahrwelt-mutable-seed" \
        seed-file "$HOME" "$target" "$source" "$home_replacement"
    }

    seed_with_replaced_line_if_missing() {
      local target="$1"
      local source="$2"
      local line_prefix="$3"
      local replacement_line="$4"

      $DRY_RUN_CMD "${mutableSeedHelper}/bin/wahrwelt-mutable-seed" \
        seed-file-replace-line "$HOME" "$target" "$source" \
        "$line_prefix" "$replacement_line"
    }

    seed_json_object() {
      local target="$1"
      local source="$2"
      local home_replacement="''${3:-}"
      local filter="''${4:-}"

      shift 4 || shift "$#"

      $DRY_RUN_CMD "${mutableSeedHelper}/bin/wahrwelt-mutable-seed" \
        seed-json-object "$HOME" "$target" "$source" "$home_replacement" \
        "${pkgs.jq}/bin/jq" "$filter" "$@"
    }
  '';
}
