# hyprlang noerror false

$hypr = ~/.config/hypr

##! MySetup
unbind = Ctrl+Super+Alt, Slash
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/end4/mysetup/keybinds.conf

##! Shared apps and utilities
unbind = Super, Return
unbind = Super, E
unbind = Super+Shift, C
unbind = Super+Shift, A
unbind = Super+Shift, N
unbind = Super+Shift, T
unbind = Super+Shift, B
unbind = Ctrl+Shift, Escape
unbind = Super, S
unbind = Super+Shift, S
unbind = Super, C
source = ~/.config/hypr/shell-common-keybinds.conf

##! Workspaces
source = ~/.config/hypr/shell-workspace-keybinds.conf
bind = $kbNextWs, exec, $wsaction workspace +1
bind = $kbPrevWs, exec, $wsaction workspace -1

##! Window
unbind = Super, F
unbind = Super, X
unbind = Super+Ctrl, Space
bindm = $kbMoveWindow, movewindow
bindm = $kbResizeWindow, resizewindow
bind = $kbCloseWindow, killactive
bind = $kbToggleWindowFloating, togglefloating
bind = $kbPinWindow, pin
bind = $kbWindowFullscreen, fullscreen, 0
bind = Super+Ctrl, Return, fullscreen, 0
bind = $kbWindowBorderedFullscreen, fullscreen, 1
