{ config, pkgs, lib, inputs, ... }:

# Host entry point. hardware-configuration.nix is host-local (not in repo).

{
  imports = [
    /etc/nixos/hardware-configuration.nix

    # Host-specific
    ./variables.nix
    # ./hashed-password.nix  # generated by install.sh (contains initialHashedPassword)
    # ./secrets/sops.nix     # enable after bootstrapping age keys (see secrets/sops.nix)

    # Shared system modules
    ../../system/boot/grub.nix
    ../../system/boot/plymouth.nix
    # ../../system/boot/secure.nix       # toggled by install.sh (Secure Boot / Lanzaboote)
    ../../system/locale.nix
    ../../system/networking.nix
    ../../system/security.nix
    # ../../system/nvidia-drivers.nix    # toggled by install.sh (NVIDIA GPU)
    ../../system/power.nix
    ../../system/hardware.nix
    ../../system/settings.nix

    # Services
    ../../services/sddm.nix
    ../../services/databases.nix
    # ../../services/observability.nix    # Grafana/Prometheus/Loki - see services/observability.nix.example
    ../../services/virtualization.nix
    ../../services/system-services.nix
    # ../../services/zapret.nix          # toggled by install.sh (DPI bypass)

    # Programs
    ../../programs/hyprland.nix
    ../../programs/thunar.nix
    ../../programs/gaming.nix
    ../../programs/fish.nix
    ../../programs/development.nix
    ../../programs/system-tools.nix

    # Packages & Users
    ../../packages/system-packages.nix
    ../../packages/dev-tools.nix
    ../../packages/fonts.nix
    ../../packages/zen-browser.nix
    # ../../packages/ctf                 # toggled by install.sh (CTF tools)
    # ../../packages/ida-mcp.nix
    # ../../packages/ida-plugins.nix
    # ../../packages/ida-pro.nix
    ../../users/user.nix

    # Custom modules
    # ../../modules/omnirouter.nix       # toggled by install.sh (local LLM router)
  ];

  boot.kernelPackages = lib.mkForce pkgs.linuxPackages_6_18;

  environment.sessionVariables = {
    NIXOS_OZONE_WL = "1";
    ELECTRON_OZONE_PLATFORM_HINT = "wayland";
  };

  system.stateVersion = config.var.stateVersion;
}
