"""Ownership-scoped offline migration for generated v1 password and brand state."""

from __future__ import annotations

import json
import os
import re
import secrets
import stat
import sys
from pathlib import Path


class MigrationError(RuntimeError):
    pass


LEGACY_MARKER = "# Generated by MySetup installer."
CANONICAL_MARKER = "# Generated by Wahrwelt installer."
LEGACY_DESCRIPTION = 'description = "Host-local MySetup NixOS wrapper";'
CANONICAL_DESCRIPTION = 'description = "Host-local Wahrwelt NixOS wrapper";'
LEGACY_HOST_CALL = "nixosConfigurations.${hostname} = mysetup.lib.mkMySetupHost {"
CANONICAL_HOST_CALL = "nixosConfigurations.${hostname} = wahrwelt.lib.mkWahrweltHost {"
WRAPPER_REQUIRED = (
    "hostVars = ./host-vars.nix;",
    "hardware = ./hardware-configuration.nix;",
    "extraModules = [ ./configuration.nix ];",
    "if builtins.pathExists ./home.nix then [ ./home.nix ] else [ ];",
)
FLAKE_URL = re.compile(
    r"github:TakuyaYagam1/(?P<repo>MySetup|wahrwelt)"
    r"(?:/(?P<ref>main|dev|noctalia-v4))?"
    r"\?dir=(?P<dir>Linux/NixOS"
    r"(?:/presets/(?:minimal|desktop|developer|personal))?)"
    r'(?=")'
)
LEGACY_PASSWORD_STANZA = """        hashedPassword =
          if builtins.pathExists ./hashed-password.nix then ./hashed-password.nix else null;"""
CANONICAL_PASSWORD_STANZA = """        hashedPasswordFile =
          if builtins.pathExists ./.wahrwelt-password-hash-enabled then
            \"/etc/wahrwelt/hashed-password\"
          else
            null;"""
PASSWORD_MARKER = ".wahrwelt-password-hash-enabled"
PASSWORD_MODULE_PATHS = (
    Path("hashed-password.nix"),
    Path("hosts/NixOS/hashed-password.nix"),
)
MAX_PASSWORD_MODULE_BYTES = 16 * 1024
SHA512_CRYPT = re.compile(
    rb"^\$6\$(?:rounds=[0-9]+\$)?[./A-Za-z0-9]{1,16}\$[./A-Za-z0-9]{86}$"
)
GENERATED_PASSWORD_MODULE = re.compile(
    rb"^\{ config, \.\.\. \}:\n\n\{\n"
    rb"  users\.users\.\$\{config\.(?:wahrwelt|mysetup)\.user\.username\}"
    rb"\.initialHashedPassword = \"([^\"\r\n]+)\";\n\}\n$"
)
FUNCTIONAL_PASSWORD_MODULE = re.compile(
    rb"^\{ config, \.\.\. \}:\n\n\{\n"
    rb"  users\.users\.\$\{config\.(?:wahrwelt|mysetup)\.user\.username\}"
    rb"\.hashedPasswordFile = \"/etc/wahrwelt/hashed-password\";\n\}\n$"
)
GITHUB_REV = re.compile(r"^[0-9a-f]{40}$")
NAR_HASH = re.compile(r"^sha256-[A-Za-z0-9+/]{43}=$")


def lstat_optional(path: Path) -> os.stat_result | None:
    try:
        return path.lstat()
    except FileNotFoundError:
        return None


def duplicate_directory(path: Path) -> int:
    match = re.fullmatch(r"/proc/self/fd/([0-9]+)", str(path))
    if match is not None:
        fd = os.dup(int(match.group(1)))
        os.set_inheritable(fd, False)
    else:
        flags = os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        fd = os.open(path, flags)
    if not stat.S_ISDIR(os.fstat(fd).st_mode):
        os.close(fd)
        raise MigrationError(
            f"ownership collision: {path} must be an ordinary directory"
        )
    return fd


def read_regular(path: Path) -> str:
    flags = os.O_RDONLY | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    fd = os.open(path, flags)
    try:
        before = os.fstat(fd)
        if not stat.S_ISREG(before.st_mode) or before.st_nlink != 1:
            raise MigrationError(
                f"ownership collision: {path} must be a singly-linked regular file"
            )
        with os.fdopen(fd, "r", encoding="utf-8", closefd=False) as source:
            content = source.read()
        after = os.fstat(fd)
        identity_fields = ("st_dev", "st_ino", "st_size", "st_mtime_ns", "st_ctime_ns")
        if any(
            getattr(before, field) != getattr(after, field) for field in identity_fields
        ):
            raise MigrationError(
                f"ownership collision: {path} changed while being read"
            )
        return content
    finally:
        os.close(fd)


def write_regular(path: Path, content: str) -> None:
    flags = os.O_WRONLY | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    fd = os.open(path, flags)
    try:
        info = os.fstat(fd)
        if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1:
            raise MigrationError(
                f"ownership collision: {path} stopped being singly-linked regular"
            )
        os.ftruncate(fd, 0)
        payload = memoryview(content.encode("utf-8"))
        while payload:
            written = os.write(fd, payload)
            if written == 0:
                raise MigrationError(f"short write while updating {path}")
            payload = payload[written:]
        os.fsync(fd)
    finally:
        os.close(fd)


def identity(info: os.stat_result) -> tuple[int, ...]:
    return (
        info.st_dev,
        info.st_ino,
        info.st_mode,
        info.st_nlink,
        info.st_uid,
        info.st_gid,
        info.st_size,
        info.st_mtime_ns,
        info.st_ctime_ns,
    )


def require_owned_private_file(path: Path, info: os.stat_result) -> None:
    if (
        not stat.S_ISREG(info.st_mode)
        or info.st_nlink != 1
        or info.st_uid != os.geteuid()
        or info.st_gid != os.getegid()
        or stat.S_IMODE(info.st_mode) != 0o600
    ):
        raise MigrationError(
            f"ownership collision: {path} must be an owned singly-linked 0600 regular file"
        )


def read_password_file(path: Path) -> tuple[bytes, os.stat_result]:
    flags = os.O_RDONLY | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    fd = os.open(path, flags)
    try:
        before = os.fstat(fd)
        require_owned_private_file(path, before)
        if before.st_size > MAX_PASSWORD_MODULE_BYTES:
            raise MigrationError(
                f"ownership collision: {path} exceeds the password data limit"
            )
        chunks: list[bytes] = []
        remaining = MAX_PASSWORD_MODULE_BYTES + 1
        while remaining > 0:
            chunk = os.read(fd, min(remaining, 4096))
            if not chunk:
                break
            chunks.append(chunk)
            remaining -= len(chunk)
        data = b"".join(chunks)
        if len(data) > MAX_PASSWORD_MODULE_BYTES:
            raise MigrationError(
                f"ownership collision: {path} exceeds the password data limit"
            )
        after = os.fstat(fd)
        if identity(before) != identity(after):
            raise MigrationError(
                f"ownership collision: {path} changed while being read"
            )
        return data, before
    finally:
        os.close(fd)


def require_plain_parent_directories(root: Path, relative: Path) -> None:
    current = root
    for component in relative.parts[:-1]:
        current /= component
        info = lstat_optional(current)
        if info is None:
            return
        if not stat.S_ISDIR(info.st_mode):
            raise MigrationError(
                f"ownership collision: {current} must be an ordinary directory"
            )


def parse_generated_password_module(path: Path) -> tuple[str, os.stat_result]:
    data, info = read_password_file(path)
    match = GENERATED_PASSWORD_MODULE.fullmatch(data)
    if match is None or SHA512_CRYPT.fullmatch(match.group(1)) is None:
        raise MigrationError(
            f"ownership collision: {path} is not an exact generated SHA512 password module"
        )
    return match.group(1).decode("ascii"), info


def read_password_evidence_file(path: Path) -> tuple[bytes, os.stat_result]:
    flags = os.O_RDONLY | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    fd = os.open(path, flags)
    try:
        before = os.fstat(fd)
        if (
            not stat.S_ISREG(before.st_mode)
            or before.st_nlink != 1
            or before.st_uid != os.geteuid()
            or before.st_gid != os.getegid()
            or before.st_size > MAX_PASSWORD_MODULE_BYTES
        ):
            raise MigrationError(
                f"ownership collision: {path} is not an owned singly-linked password module"
            )
        chunks: list[bytes] = []
        remaining = MAX_PASSWORD_MODULE_BYTES + 1
        while remaining > 0:
            chunk = os.read(fd, min(remaining, 4096))
            if not chunk:
                break
            chunks.append(chunk)
            remaining -= len(chunk)
        data = b"".join(chunks)
        after = os.fstat(fd)
        if len(data) > MAX_PASSWORD_MODULE_BYTES or identity(before) != identity(after):
            raise MigrationError(
                f"ownership collision: {path} changed while classifying password evidence"
            )
        return data, before
    finally:
        os.close(fd)


def password_evidence(root: Path, raw_target: str) -> str:
    kinds: list[str] = []
    try:
        for relative in PASSWORD_MODULE_PATHS:
            require_plain_parent_directories(root, relative)
            path = root / relative
            if lstat_optional(path) is None:
                continue
            data, info = read_password_evidence_file(path)
            mode = stat.S_IMODE(info.st_mode)
            generated = GENERATED_PASSWORD_MODULE.fullmatch(data)
            if (
                mode == 0o600
                and generated is not None
                and SHA512_CRYPT.fullmatch(generated.group(1)) is not None
            ):
                kinds.append("legacy")
                continue
            if mode == 0o644 and FUNCTIONAL_PASSWORD_MODULE.fullmatch(data) is not None:
                kinds.append("completed")
                continue
            return "unrecognized"
    except (MigrationError, OSError, UnicodeError, ValueError):
        return "unrecognized"

    if not kinds:
        return "absent"
    if "legacy" in kinds:
        return "legacy"
    try:
        target = clean_external_target(raw_target)
        if read_external_hash(target) is not None:
            return "completed"
    except (MigrationError, OSError, UnicodeError, ValueError):
        pass
    return "unrecognized"


def inspect_password_module(root: Path) -> tuple[Path, str, os.stat_result] | None:
    found: list[tuple[Path, str, os.stat_result]] = []
    for relative in PASSWORD_MODULE_PATHS:
        require_plain_parent_directories(root, relative)
        path = root / relative
        info = lstat_optional(path)
        if info is None:
            continue
        if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1:
            raise MigrationError(
                f"ownership collision: {path} must be a singly-linked regular file"
            )
        password_hash, verified = parse_generated_password_module(path)
        if identity(info) != identity(verified):
            raise MigrationError(
                f"ownership collision: {path} changed during inspection"
            )
        found.append((path, password_hash, verified))
    if len(found) > 1:
        raise MigrationError(
            "ownership collision: multiple generated password module sources exist"
        )
    return found[0] if found else None


def inspect_legacy_password_marker(root: Path) -> None:
    marker = root / PASSWORD_MARKER
    if lstat_optional(marker) is not None:
        raise MigrationError(
            f"ownership collision: legacy password stanza coexists with marker {marker}"
        )


def password_stanza_kind(source: str) -> str:
    legacy_count = source.count(LEGACY_PASSWORD_STANZA)
    canonical_count = source.count(CANONICAL_PASSWORD_STANZA)
    password_tokens = source.count("hashedPassword")
    if legacy_count == 1 and canonical_count == 0 and password_tokens == 1:
        return "legacy"
    if canonical_count == 1 and legacy_count == 0 and password_tokens == 1:
        return "canonical"
    if legacy_count == 0 and canonical_count == 0 and password_tokens == 0:
        return "absent"
    return "unrecognized"


def reject_json_constant(value: str) -> object:
    raise MigrationError(f"flake.lock contains invalid JSON constant {value}")


def reject_duplicate_json_keys(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise MigrationError(f"flake.lock contains duplicate key {key!r}")
        result[key] = value
    return result


def wrapper_kind(source: str) -> str:
    legacy_markers = source.count(LEGACY_MARKER)
    canonical_markers = source.count(CANONICAL_MARKER)
    if legacy_markers + canonical_markers != 1:
        return "unrecognized"

    kind = "v1" if legacy_markers == 1 else "v2"
    name = "mysetup" if kind == "v1" else "wahrwelt"
    description = LEGACY_DESCRIPTION if kind == "v1" else CANONICAL_DESCRIPTION
    host_call = LEGACY_HOST_CALL if kind == "v1" else CANONICAL_HOST_CALL
    input_shapes = (f"    {name} = {{", f"    {name}.url = ")
    output_shapes = (
        f"  outputs = inputs@{{ {name}, ... }}:",
        f"  outputs = {{ {name}, ... }}:",
    )

    if source.count(description) != 1 or source.count(host_call) != 1:
        return "unrecognized"
    if sum(source.count(token) for token in input_shapes) != 1:
        return "unrecognized"
    if sum(source.count(token) for token in output_shapes) != 1:
        return "unrecognized"
    if any(source.count(token) != 1 for token in WRAPPER_REQUIRED):
        return "unrecognized"
    if password_stanza_kind(source) == "unrecognized":
        return "unrecognized"

    urls = list(FLAKE_URL.finditer(source))
    expected_repo = "MySetup" if kind == "v1" else "wahrwelt"
    if len(urls) != 1 or urls[0].group("repo") != expected_repo:
        return "unrecognized"
    return kind


def classify(root: Path) -> str:
    flake = root / "flake.nix"
    info = lstat_optional(flake)
    if info is None or not stat.S_ISREG(info.st_mode) or info.st_nlink != 1:
        return "unrecognized"
    try:
        source = read_regular(flake)
        kind = wrapper_kind(source)
        if kind in ("v1", "v2") and password_stanza_kind(source) == "legacy":
            return f"{kind}-password"
        return kind
    except (OSError, UnicodeError):
        return "unrecognized"


def replace_single(source: str, old: str, new: str, label: str) -> str:
    count = source.count(old)
    if count != 1:
        raise MigrationError(
            f"ownership collision: generated wrapper requires one {label}; found {count}"
        )
    return source.replace(old, new, 1)


def rewrite_wrapper(source: str) -> str:
    brand_kind = wrapper_kind(source)
    password_kind = password_stanza_kind(source)
    if brand_kind not in ("v1", "v2") or password_kind == "unrecognized":
        raise MigrationError(
            "ownership collision: exact generated wrapper evidence is absent"
        )
    if brand_kind == "v2" and password_kind != "legacy":
        raise MigrationError("ownership collision: wrapper has no v1_to_v2 changes")

    migrated = source
    if brand_kind == "v1":
        migrated = replace_single(
            migrated, LEGACY_MARKER, CANONICAL_MARKER, "v1 marker"
        )
        migrated = replace_single(
            migrated, LEGACY_DESCRIPTION, CANONICAL_DESCRIPTION, "v1 description"
        )
        migrated = replace_single(
            migrated, LEGACY_HOST_CALL, CANONICAL_HOST_CALL, "v1 host call"
        )

        input_shapes = (
            ("    mysetup = {", "    wahrwelt = {"),
            ("    mysetup.url = ", "    wahrwelt.url = "),
        )
        matching_inputs = [(old, new) for old, new in input_shapes if old in migrated]
        if len(matching_inputs) != 1:
            raise MigrationError(
                "ownership collision: generated v1 input binding is ambiguous"
            )
        migrated = replace_single(migrated, *matching_inputs[0], "v1 input binding")

        output_shapes = (
            (
                "  outputs = inputs@{ mysetup, ... }:",
                "  outputs = inputs@{ wahrwelt, ... }:",
            ),
            ("  outputs = { mysetup, ... }:", "  outputs = { wahrwelt, ... }:"),
        )
        matching_outputs = [(old, new) for old, new in output_shapes if old in migrated]
        if len(matching_outputs) != 1:
            raise MigrationError(
                "ownership collision: generated v1 output binding is ambiguous"
            )
        migrated = replace_single(migrated, *matching_outputs[0], "v1 output binding")

        urls = list(FLAKE_URL.finditer(migrated))
        if len(urls) != 1 or urls[0].group("repo") != "MySetup":
            raise MigrationError("ownership collision: generated v1 URL is ambiguous")
        url = urls[0]
        canonical_url = url.group(0).replace(
            "github:TakuyaYagam1/MySetup", "github:TakuyaYagam1/wahrwelt", 1
        )
        migrated = migrated[: url.start()] + canonical_url + migrated[url.end() :]

    if password_kind == "legacy":
        migrated = replace_single(
            migrated,
            LEGACY_PASSWORD_STANZA,
            CANONICAL_PASSWORD_STANZA,
            "legacy password stanza",
        )

    if wrapper_kind(migrated) != "v2" or password_stanza_kind(migrated) == "legacy":
        raise MigrationError(
            "ownership collision: migrated wrapper failed v2 validation"
        )
    return migrated


def clean_external_target(raw_target: str) -> Path:
    target = Path(raw_target)
    absolute = Path(os.path.abspath(raw_target))
    if (
        target != absolute
        or target.name != "hashed-password"
        or target.parent.name != "wahrwelt"
    ):
        raise MigrationError(
            "ownership collision: external password target must be an absolute wahrwelt/hashed-password path"
        )
    return target


def open_external_parent(target: Path, create: bool) -> int | None:
    parent = target.parent
    grandparent = parent.parent
    flags = os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    grand_fd = os.open(grandparent, flags)
    try:
        grand_info = os.fstat(grand_fd)
        if (
            grand_info.st_uid != os.geteuid()
            or grand_info.st_gid != os.getegid()
            or stat.S_IMODE(grand_info.st_mode) & 0o022
        ):
            raise MigrationError(
                f"ownership collision: external password ancestor {grandparent} is not owned and protected"
            )
        try:
            parent_info = os.stat(parent.name, dir_fd=grand_fd, follow_symlinks=False)
        except FileNotFoundError:
            if not create:
                return None
            try:
                os.mkdir(parent.name, 0o700, dir_fd=grand_fd)
            except FileExistsError:
                pass
            parent_info = os.stat(parent.name, dir_fd=grand_fd, follow_symlinks=False)
        if not stat.S_ISDIR(parent_info.st_mode):
            raise MigrationError(
                f"ownership collision: external password parent {parent} is not an ordinary directory"
            )
        parent_fd = os.open(parent.name, flags, dir_fd=grand_fd)
        opened = os.fstat(parent_fd)
        visible = os.stat(parent.name, dir_fd=grand_fd, follow_symlinks=False)
        if (
            (opened.st_dev, opened.st_ino) != (visible.st_dev, visible.st_ino)
            or opened.st_uid != os.geteuid()
            or opened.st_gid != os.getegid()
            or stat.S_IMODE(opened.st_mode) != 0o700
        ):
            os.close(parent_fd)
            raise MigrationError(
                f"ownership collision: external password parent {parent} is not owned private 0700"
            )
        return parent_fd
    finally:
        os.close(grand_fd)


def read_external_hash(target: Path, create_parent: bool = False) -> str | None:
    parent_fd = open_external_parent(target, create_parent)
    if parent_fd is None:
        return None
    try:
        try:
            visible = os.stat(target.name, dir_fd=parent_fd, follow_symlinks=False)
        except FileNotFoundError:
            return None
        flags = os.O_RDONLY | os.O_CLOEXEC
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        fd = os.open(target.name, flags, dir_fd=parent_fd)
        try:
            before = os.fstat(fd)
            require_owned_private_file(target, before)
            if (before.st_dev, before.st_ino) != (visible.st_dev, visible.st_ino):
                raise MigrationError(
                    f"ownership collision: external password target {target} changed while opening"
                )
            if before.st_size > MAX_PASSWORD_MODULE_BYTES:
                raise MigrationError(
                    f"ownership collision: external password target {target} exceeds the data limit"
                )
            data = b""
            while len(data) <= MAX_PASSWORD_MODULE_BYTES:
                chunk = os.read(fd, 4096)
                if not chunk:
                    break
                data += chunk
            after = os.fstat(fd)
            if len(data) > MAX_PASSWORD_MODULE_BYTES or identity(before) != identity(
                after
            ):
                raise MigrationError(
                    f"ownership collision: external password target {target} changed while reading"
                )
        finally:
            os.close(fd)
    finally:
        os.close(parent_fd)
    payload = data[:-1] if data.endswith(b"\n") else data
    if SHA512_CRYPT.fullmatch(payload) is None:
        raise MigrationError(
            f"ownership collision: external password target {target} is not a raw SHA512 hash"
        )
    return payload.decode("ascii")


def publish_external_hash(target: Path, password_hash: str) -> None:
    existing = read_external_hash(target, create_parent=True)
    if existing is not None:
        if existing != password_hash:
            raise MigrationError(
                f"ownership collision: external password target {target} disagrees with generated module"
            )
        return

    parent_fd = open_external_parent(target, create=True)
    assert parent_fd is not None
    temporary = f".hashed-password.{secrets.token_hex(8)}"
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    fd = os.open(temporary, flags, 0o600, dir_fd=parent_fd)
    linked = False
    try:
        os.fchmod(fd, 0o600)
        os.fchown(fd, os.geteuid(), os.getegid())
        payload = memoryview((password_hash + "\n").encode("ascii"))
        while payload:
            written = os.write(fd, payload)
            if written == 0:
                raise MigrationError(
                    f"short write while publishing external password target {target}"
                )
            payload = payload[written:]
        os.fsync(fd)
        try:
            os.link(
                temporary,
                target.name,
                src_dir_fd=parent_fd,
                dst_dir_fd=parent_fd,
                follow_symlinks=False,
            )
            linked = True
        except FileExistsError:
            pass
    finally:
        os.close(fd)
        try:
            os.unlink(temporary, dir_fd=parent_fd)
        except FileNotFoundError:
            pass
        os.fsync(parent_fd)
        os.close(parent_fd)
    published = read_external_hash(target)
    if published != password_hash:
        collision = " appeared concurrently" if not linked else " failed verification"
        raise MigrationError(
            f"ownership collision: external password target {target}{collision}"
        )


def validate_password_marker(root: Path) -> bool:
    marker = root / PASSWORD_MARKER
    info = lstat_optional(marker)
    if info is None:
        return False
    if (
        not stat.S_ISREG(info.st_mode)
        or info.st_nlink != 1
        or info.st_uid != os.geteuid()
        or info.st_gid != os.getegid()
        or stat.S_IMODE(info.st_mode) != 0o644
        or info.st_size != 0
    ):
        raise MigrationError(
            f"ownership collision: password marker {marker} must be an owned empty 0644 regular file"
        )
    return True


def create_password_marker(root: Path) -> None:
    marker = root / PASSWORD_MARKER
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    try:
        fd = os.open(marker, flags, 0o644)
    except FileExistsError as error:
        raise MigrationError(
            f"ownership collision: password marker already exists at {marker}"
        ) from error
    try:
        os.fchmod(fd, 0o644)
        os.fchown(fd, os.geteuid(), os.getegid())
        os.fsync(fd)
    finally:
        os.close(fd)
    validate_password_marker(root)


def remove_password_module(candidate: tuple[Path, str, os.stat_result]) -> None:
    path, _password_hash, expected = candidate
    parent_fd = duplicate_directory(path.parent)
    try:
        visible = os.stat(path.name, dir_fd=parent_fd, follow_symlinks=False)
        if identity(visible) != identity(expected):
            raise MigrationError(
                f"ownership collision: password module {path} changed before removal"
            )
        os.unlink(path.name, dir_fd=parent_fd)
        os.fsync(parent_fd)
    finally:
        os.close(parent_fd)


def publish_password(root: Path, raw_target: str) -> None:
    if classify(root) not in ("v1-password", "v2-password"):
        raise MigrationError(
            "ownership collision: exact legacy password stanza evidence is absent"
        )
    inspect_legacy_password_marker(root)
    candidate = inspect_password_module(root)
    if candidate is None:
        return
    target = clean_external_target(raw_target)
    publish_external_hash(target, candidate[1])


def load_lock(path: Path) -> dict[str, object]:
    try:
        decoded = json.loads(
            read_regular(path),
            object_pairs_hook=reject_duplicate_json_keys,
            parse_constant=reject_json_constant,
        )
    except (json.JSONDecodeError, OSError, UnicodeError, ValueError) as error:
        raise MigrationError(
            f"ownership collision: flake.lock is not strict JSON: {error}"
        ) from error
    if type(decoded) is not dict:
        raise MigrationError(
            "ownership collision: flake.lock root must be a JSON object"
        )
    return decoded


def lock_nodes(lock: dict[str, object]) -> tuple[dict[str, object], dict[str, object]]:
    nodes = lock.get("nodes")
    if type(nodes) is not dict:
        raise MigrationError(
            "ownership collision: flake.lock.nodes must be a JSON object"
        )
    root = nodes.get("root")
    if type(root) is not dict or type(root.get("inputs")) is not dict:
        raise MigrationError("ownership collision: flake.lock root inputs are missing")
    return nodes, root["inputs"]


def wrapper_lock_source(source: str, expected_repo: str) -> tuple[str, str | None]:
    urls = list(FLAKE_URL.finditer(source))
    if len(urls) != 1 or urls[0].group("repo") != expected_repo:
        raise MigrationError(
            "ownership collision: generated wrapper source identity is ambiguous"
        )
    return urls[0].group("dir"), urls[0].group("ref")


def require_lock_source(
    node: object,
    expected_repo: str,
    expected_dir: str,
    expected_ref: str | None,
) -> dict[str, object]:
    if type(node) is not dict:
        raise MigrationError("ownership collision: generated lock node must be an object")
    if set(node) - {"inputs", "locked", "original"}:
        raise MigrationError(
            "ownership collision: generated lock node contains unknown fields"
        )
    if "inputs" in node and type(node["inputs"]) is not dict:
        raise MigrationError(
            "ownership collision: generated lock node inputs must be an object"
        )

    locked = node.get("locked")
    original = node.get("original")
    if type(locked) is not dict or type(original) is not dict:
        raise MigrationError(
            "ownership collision: generated lock source metadata is missing"
        )
    locked_keys = {
        "dir",
        "lastModified",
        "narHash",
        "owner",
        "repo",
        "rev",
        "type",
    }
    original_keys = {"dir", "owner", "repo", "type"}
    if expected_ref is not None:
        original_keys.add("ref")
    if set(locked) != locked_keys or set(original) != original_keys:
        raise MigrationError(
            "ownership collision: generated lock source metadata has an unexpected shape"
        )
    if (
        locked.get("type") != "github"
        or original.get("type") != "github"
        or locked.get("owner") != "TakuyaYagam1"
        or original.get("owner") != "TakuyaYagam1"
        or locked.get("repo") != expected_repo
        or original.get("repo") != expected_repo
        or locked.get("dir") != expected_dir
        or original.get("dir") != expected_dir
        or original.get("ref") != expected_ref
    ):
        raise MigrationError(
            "ownership collision: generated lock source does not match the wrapper URL"
        )
    last_modified = locked.get("lastModified")
    if type(last_modified) is not int or last_modified < 0:
        raise MigrationError(
            "ownership collision: generated lock lastModified must be a non-negative integer"
        )
    revision = locked.get("rev")
    if type(revision) is not str or GITHUB_REV.fullmatch(revision) is None:
        raise MigrationError(
            "ownership collision: generated lock rev must be a full Git revision"
        )
    nar_hash = locked.get("narHash")
    if type(nar_hash) is not str or NAR_HASH.fullmatch(nar_hash) is None:
        raise MigrationError(
            "ownership collision: generated lock narHash must be an exact SHA256 SRI hash"
        )
    return node


def migrated_lock_payload(path: Path, source: str) -> str:
    lock = load_lock(path)
    nodes, inputs = lock_nodes(lock)
    if "mysetup" not in inputs or inputs["mysetup"] != "mysetup":
        raise MigrationError("ownership collision: exact v1 root lock input is absent")
    if "mysetup" not in nodes:
        raise MigrationError("ownership collision: exact v1 lock node is absent")
    if "wahrwelt" in inputs or "wahrwelt" in nodes:
        raise MigrationError("ownership collision: v1 and v2 lock entries coexist")

    expected_dir, expected_ref = wrapper_lock_source(source, "MySetup")
    node = require_lock_source(
        nodes["mysetup"], "MySetup", expected_dir, expected_ref
    )
    locked = node["locked"]
    original = node["original"]
    assert type(locked) is dict and type(original) is dict
    locked["repo"] = "wahrwelt"
    original["repo"] = "wahrwelt"
    inputs["wahrwelt"] = "wahrwelt"
    del inputs["mysetup"]
    nodes["wahrwelt"] = nodes.pop("mysetup")
    return json.dumps(lock, indent=2, sort_keys=True) + "\n"


def validate_lock(path: Path, source: str) -> None:
    lock = load_lock(path)
    nodes, inputs = lock_nodes(lock)
    if "mysetup" in inputs or "mysetup" in nodes:
        raise MigrationError("v1_to_v2 left a legacy lock entry")
    if inputs.get("wahrwelt") != "wahrwelt" or "wahrwelt" not in nodes:
        raise MigrationError("v1_to_v2 left an incomplete v2 lock entry")
    expected_dir, expected_ref = wrapper_lock_source(source, "wahrwelt")
    require_lock_source(
        nodes["wahrwelt"], "wahrwelt", expected_dir, expected_ref
    )


def migrate(root: Path, raw_target: str | None = None) -> None:
    kind = classify(root)
    if kind not in ("v1", "v1-password", "v2-password"):
        raise MigrationError(
            "ownership collision: exact generated v1_to_v2 evidence is absent"
        )
    flake = root / "flake.nix"
    source = read_regular(flake)
    migrated_source = rewrite_wrapper(source)
    migrated_lock = None
    if kind.startswith("v1"):
        migrated_lock = migrated_lock_payload(root / "flake.lock", source)
    candidate = None
    target = None
    if kind.endswith("-password"):
        inspect_legacy_password_marker(root)
        candidate = inspect_password_module(root)
        if candidate is not None:
            if raw_target is None:
                raise MigrationError(
                    "external password target is required for generated module migration"
                )
            target = clean_external_target(raw_target)
            external_hash = read_external_hash(target)
            if external_hash != candidate[1]:
                raise MigrationError(
                    f"ownership collision: external password target {target} does not match generated module"
                )

    write_regular(flake, migrated_source)
    if migrated_lock is not None:
        write_regular(root / "flake.lock", migrated_lock)
    if candidate is not None:
        remove_password_module(candidate)
        create_password_marker(root)
    validate(root, raw_target)


def validate(root: Path, raw_target: str | None = None) -> None:
    if classify(root) != "v2":
        raise MigrationError("v1_to_v2 left an unrecognized generated v2 wrapper")
    source = read_regular(root / "flake.nix")
    validate_lock(root / "flake.lock", source)
    candidate = inspect_password_module(root)
    if candidate is not None:
        raise MigrationError(
            f"v1_to_v2 left generated password module at {candidate[0]}"
        )
    marker_exists = validate_password_marker(root)
    if marker_exists:
        if password_stanza_kind(source) != "canonical" or raw_target is None:
            raise MigrationError(
                "v1_to_v2 left an incomplete external password contract"
            )
        target = clean_external_target(raw_target)
        if read_external_hash(target) is None:
            raise MigrationError(
                f"v1_to_v2 external password target is missing: {target}"
            )


def main(arguments: list[str]) -> int:
    if len(arguments) < 2:
        raise MigrationError(
            "usage: brand.py classify ROOT | password-evidence ROOT TARGET | publish-password ROOT TARGET | migrate|validate ROOT [TARGET]"
        )
    command, raw_root, *rest = arguments
    root = Path(os.path.abspath(raw_root))
    if command == "classify":
        if rest:
            raise MigrationError("classify accepts only ROOT")
        print(classify(root))
        return 0
    if command == "password-evidence":
        if len(rest) != 1:
            raise MigrationError("password-evidence requires ROOT and TARGET")
        print(password_evidence(root, rest[0]))
        return 0
    if command == "publish-password":
        if len(rest) != 1:
            raise MigrationError("publish-password requires ROOT and TARGET")
        publish_password(root, rest[0])
        return 0
    if command == "migrate":
        if len(rest) > 1:
            raise MigrationError("migrate accepts ROOT and optional TARGET")
        migrate(root, rest[0] if rest else None)
        return 0
    if command == "validate":
        if len(rest) > 1:
            raise MigrationError("validate accepts ROOT and optional TARGET")
        validate(root, rest[0] if rest else None)
        return 0
    raise MigrationError(f"unknown v1_to_v2 command: {command}")


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except (MigrationError, OSError, UnicodeError, ValueError) as error:
        print(f"Wahrwelt v1_to_v2 migration error: {error}", file=sys.stderr)
        raise SystemExit(1) from error
