{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.services.omnirouter;

  ensureServerEnv = pkgs.writeShellScript "omnirouter-ensure-server-env" ''
    set -eu

    data_dir=/var/lib/omnirouter
    env_file="$data_dir/server.env"

    mkdir -p "$data_dir"
    umask 077
    if [ ! -e "$env_file" ]; then
      {
        echo "# Generated by MySetup NixOS service - do not delete"
        echo "# OmniRoute encrypted credentials depend on STORAGE_ENCRYPTION_KEY"
      } > "$env_file"
    fi

    ensure_secret() {
      key="$1"
      bytes="$2"
      if ! ${pkgs.gnugrep}/bin/grep -q "^$key=" "$env_file"; then
        printf '%s=%s\n' "$key" "$(${pkgs.openssl}/bin/openssl rand -hex "$bytes")" >> "$env_file"
      fi
    }

    ensure_secret JWT_SECRET 64
    ensure_secret STORAGE_ENCRYPTION_KEY 32
    if ! ${pkgs.gnugrep}/bin/grep -q '^STORAGE_ENCRYPTION_KEY_VERSION=' "$env_file"; then
      printf '%s\n' 'STORAGE_ENCRYPTION_KEY_VERSION=v1' >> "$env_file"
    fi
    ensure_secret API_KEY_SECRET 32
  '';
in
{
  options.services.omnirouter = {
    enable = lib.mkEnableOption "OmniRouter service";

    package = lib.mkOption {
      type = lib.types.package;
      description = "Binary package for OmniRouter";
      default = pkgs.omnirouter;
    };

    extraArgs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "Extra CLI args for omnirouter";
    };

    ensureServerEnv = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Ensure /var/lib/omnirouter/server.env contains persistent OmniRoute
        secrets before startup. This prevents STORAGE_ENCRYPTION_KEY loss across
        package upgrades. If credentials were already encrypted with a lost key,
        re-authenticate providers or run omniroute reset-encrypted-columns.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];

    systemd.services.omnirouter = {
      description = "OmniRouter LLM router";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      path = [
        pkgs.nodejs_22
        cfg.package
      ];

      serviceConfig = {
        ExecStartPre = lib.mkIf cfg.ensureServerEnv ensureServerEnv;
        ExecStart = ''
          ${cfg.package}/bin/omnirouter \
            ${lib.escapeShellArgs cfg.extraArgs}
        '';
        Restart = "on-failure";

        Environment = [
          "HOME=/var/lib/omnirouter"
          "DATA_DIR=/var/lib/omnirouter"
          "APP_LOG_FILE_PATH=/var/lib/omnirouter/logs/application/app.log"
          "OMNIROUTE_NO_UPDATE_NOTIFIER=1"
        ];

        DynamicUser = true;
        StateDirectory = "omnirouter";
        WorkingDirectory = "/var/lib/omnirouter";

        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        UMask = "0077";
      };
    };
  };
}
