bind = Super+Shift, W, exec, $hypr/scripts/shell-selector.sh toggle

bind = $kbTerminal, exec, app2unit -- $terminal
bind = $kbZen, exec, app2unit -- $zen
bind = $kbCursor, exec, app2unit -- $cursor
bind = $kbVscode, exec, app2unit -- $vscode
bind = $kbGoland, exec, app2unit -- $goland
bind = $kbDatagrip, exec, app2unit -- $datagrip
bind = $kbAntigravity, exec, app2unit -- $antigravity
bind = $kbAmneziaVPN, exec, app2unit -- $amneziaVPN
bind = $kbv2rayN, exec, app2unit -- $v2rayN
bind = $kbVesktop, exec, app2unit -- $vesktop
bind = $kbSpotify, exec, $hypr/scripts/spotify-toggle.sh
bind = $kbTelegram, exec, app2unit -- $telegram
bind = $kbBtop, exec, app2unit -- $btop
bind = $kbFileExplorer, exec, app2unit -- $fileExplorer
bind = Super+Alt, E, exec, app2unit -- $fileExplorer
bind = Ctrl+Alt, V, exec, app2unit -- pavucontrol

bindl = Super, S, exec, $hypr/scripts/screenshot.sh full
bind = Super+Shift, S, exec, $hypr/scripts/screenshot.sh region
bind = Super+Shift+Alt, S, exec, $hypr/scripts/screenshot.sh edit
bind = Super, C, exec, hyprpicker -a

bind = $kbRecord, exec, $hypr/scripts/record-toggle.sh
