#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
helper="$repo_root/Linux/NixOS/system/migrations/v1_to_v2/brand.py"
codex_tmp="${CODEX_TMP_DIR:-$HOME/.codex/.tmp}"
mkdir -p "$codex_tmp"
chmod 0700 "$codex_tmp"
test_root="$(mktemp -d "$codex_tmp/nix-brand-v1-to-v2.XXXXXX")"
trap 'rm -rf "$test_root"' EXIT

fixture="$test_root/etc/nixos"
mkdir -p "$fixture"
external_hash="$test_root/etc/wahrwelt/hashed-password"
test_hash="\$6\$rounds=5000\$testsalt\$$(printf 'A%.0s' {1..86})"
other_hash="\$6\$rounds=5000\$othersalt\$$(printf 'B%.0s' {1..86})"

write_password_module() {
    local path="$1"
    local namespace="$2"
    local hash="$3"

    mkdir -p "$(dirname "$path")"
    printf '%s\n' \
        '{ config, ... }:' \
        '' \
        '{' \
        "  users.users.\${config.$namespace.user.username}.initialHashedPassword = \"$hash\";" \
        '}' > "$path"
    chmod 0600 "$path"
}

expect_password_failure() {
    local root="$1"
    local target="$2"
    local label="$3"
    local output

    if output="$(python3 "$helper" publish-password "$root" "$target" 2>&1)"; then
        printf 'FAIL v1_to_v2 accepted %s\n' "$label" >&2
        exit 1
    fi
    if [[ "$output" == *"$test_hash"* || "$output" == *"$other_hash"* ]]; then
        printf 'FAIL v1_to_v2 leaked a password hash while rejecting %s\n' "$label" >&2
        exit 1
    fi
}

# The fixture must preserve Nix interpolation such as ${hostname} literally.
# shellcheck disable=SC2016
v1_flake='{
  # Generated by MySetup installer.
  # lock mode: managed
  # preset: personal
  # supported compatibility alias in documentation: mysetup
  description = "Host-local MySetup NixOS wrapper";

  inputs = {
    mysetup.url = "github:TakuyaYagam1/MySetup/dev?dir=Linux/NixOS/presets/personal";
  };

  outputs = inputs@{ mysetup, ... }:
    let
      system = "x86_64-linux";
      hostname = "NixOS";
    in
    {
      nixosConfigurations.${hostname} = mysetup.lib.mkMySetupHost {
        inherit system hostname;
        hostVars = ./host-vars.nix;
        hardware = ./hardware-configuration.nix;
        hashedPassword =
          if builtins.pathExists ./hashed-password.nix then ./hashed-password.nix else null;
        secretsDir = null;
        extraModules = [ ./configuration.nix ];
        homeExtraModules =
          if builtins.pathExists ./home.nix then [ ./home.nix ] else [ ];
      };
    };
}
'
# The fixture must preserve Nix interpolation such as ${hostname} literally.
# shellcheck disable=SC2016
v2_password_flake='{
  # Generated by Wahrwelt installer.
  # lock mode: managed
  # preset: personal
  # supported compatibility alias in documentation: mysetup
  description = "Host-local Wahrwelt NixOS wrapper";

  inputs = {
    wahrwelt.url = "github:TakuyaYagam1/wahrwelt/main?dir=Linux/NixOS/presets/personal";
  };

  outputs = inputs@{ wahrwelt, ... }:
    let
      system = "x86_64-linux";
      hostname = "NixOS";
    in
    {
      nixosConfigurations.${hostname} = wahrwelt.lib.mkWahrweltHost {
        inherit system hostname;
        hostVars = ./host-vars.nix;
        hardware = ./hardware-configuration.nix;
        hashedPassword =
          if builtins.pathExists ./hashed-password.nix then ./hashed-password.nix else null;
        secretsDir = null;
        extraModules = [ ./configuration.nix ];
        homeExtraModules =
          if builtins.pathExists ./home.nix then [ ./home.nix ] else [ ];
      };
    };
}
'
printf '%s' "$v1_flake" > "$fixture/flake.nix"
printf '%s\n' '{ custom.mysetup = "user-owned"; }' > "$fixture/configuration.nix"
printf '%s\n' '{ home.sessionVariables.MYSETUP_COMPAT = "mysetup"; }' > "$fixture/home.nix"
printf '%s\n' '{ userNote = "mysetup alias remains supported"; }' > "$fixture/host-vars.nix"
printf '%s\n' '{ ... }: { }' > "$fixture/hardware-configuration.nix"
write_password_module "$fixture/hashed-password.nix" mysetup "$test_hash"
printf '%s\n' '{
  "nodes": {
    "mysetup": {
      "locked": {
        "dir": "Linux/NixOS/presets/personal",
        "lastModified": 1234567890,
        "narHash": "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
        "owner": "TakuyaYagam1",
        "repo": "MySetup",
        "rev": "0123456789abcdef0123456789abcdef01234567",
        "type": "github"
      },
      "original": {
        "dir": "Linux/NixOS/presets/personal",
        "owner": "TakuyaYagam1",
        "ref": "dev",
        "repo": "MySetup",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "mysetup": "mysetup",
        "user-input": "user-input"
      }
    },
    "user-input": {
      "locked": {
        "narHash": "sha256-BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=",
        "note": "mysetup is a supported compatibility alias"
      }
    }
  },
  "root": "root",
  "version": 7
}' > "$fixture/flake.lock"

configuration_before="$(sha256sum "$fixture/configuration.nix")"
home_before="$(sha256sum "$fixture/home.nix")"
host_vars_before="$(sha256sum "$fixture/host-vars.nix")"
locked_before="$(jq -c '.nodes.mysetup.locked' "$fixture/flake.lock")"
original_before="$(jq -c '.nodes.mysetup.original' "$fixture/flake.lock")"
user_node_before="$(jq -c '.nodes["user-input"]' "$fixture/flake.lock")"

test "$(python3 "$helper" classify "$fixture")" = v1-password
test "$(python3 "$helper" password-evidence "$fixture" "$external_hash")" = legacy
publish_output="$(python3 "$helper" publish-password "$fixture" "$external_hash" 2>&1)"
test -z "$publish_output"
test "$(stat -c %a "$external_hash")" = 600
printf '%s\n' "$test_hash" > "$test_root/expected-hash"
cmp -s "$test_root/expected-hash" "$external_hash"
migrate_output="$(python3 "$helper" migrate "$fixture" "$external_hash" 2>&1)"
test -z "$migrate_output"
test "$(python3 "$helper" classify "$fixture")" = v2
python3 "$helper" validate "$fixture" "$external_hash"

test "$configuration_before" = "$(sha256sum "$fixture/configuration.nix")"
test "$home_before" = "$(sha256sum "$fixture/home.nix")"
test "$host_vars_before" = "$(sha256sum "$fixture/host-vars.nix")"
test "$(printf '%s' "$locked_before" | jq -c '.repo = "wahrwelt"')" = \
    "$(jq -c '.nodes.wahrwelt.locked' "$fixture/flake.lock")"
test "$(printf '%s' "$original_before" | jq -c '.repo = "wahrwelt"')" = \
    "$(jq -c '.nodes.wahrwelt.original' "$fixture/flake.lock")"
test "$user_node_before" = "$(jq -c '.nodes["user-input"]' "$fixture/flake.lock")"
jq -e '
  .nodes.root.inputs.wahrwelt == "wahrwelt" and
  (.nodes.root.inputs | has("mysetup") | not) and
  (.nodes | has("wahrwelt")) and
  (.nodes | has("mysetup") | not)
' "$fixture/flake.lock" >/dev/null
grep -Fq '# supported compatibility alias in documentation: mysetup' "$fixture/flake.nix"
grep -Fq 'github:TakuyaYagam1/wahrwelt/dev?dir=Linux/NixOS/presets/personal' "$fixture/flake.nix"
grep -Fq 'hashedPasswordFile =' "$fixture/flake.nix"
grep -Fq '"/etc/wahrwelt/hashed-password"' "$fixture/flake.nix"
if grep -Fq 'hashedPassword =' "$fixture/flake.nix"; then
    printf 'FAIL v1_to_v2 retained the legacy password argument\n' >&2
    exit 1
fi
test -f "$fixture/.wahrwelt-password-hash-enabled"
test ! -s "$fixture/.wahrwelt-password-hash-enabled"
test ! -e "$fixture/hashed-password.nix"
test "$(python3 "$helper" password-evidence "$fixture" "$external_hash")" = absent
if rg -q --fixed-strings -- "$test_hash" "$fixture"; then
    printf 'FAIL v1_to_v2 retained the password hash in the migrated candidate\n' >&2
    exit 1
fi

offline_source="$test_root/offline-source"
offline_source_flake="$offline_source/Linux/NixOS/presets/personal/flake.nix"
mkdir -p "$(dirname "$offline_source_flake")"
printf '%s\n' \
    '{' \
    '  outputs = { self }: {' \
    '    lib.mkWahrweltHost = args: args;' \
    '  };' \
    '}' > "$offline_source_flake"
offline_store_path="$(nix store add-path --name source "$offline_source")"
test -n "$offline_store_path"
offline_nar_hash="$(nix hash path "$offline_source")"

offline_fixture="$test_root/offline-fixture"
mkdir -p "$offline_fixture"
printf '%s' "$v1_flake" > "$offline_fixture/flake.nix"
jq -n --arg narHash "$offline_nar_hash" '
  {
    nodes: {
      mysetup: {
        locked: {
          dir: "Linux/NixOS/presets/personal",
          lastModified: 1234567890,
          narHash: $narHash,
          owner: "TakuyaYagam1",
          repo: "MySetup",
          rev: "0123456789abcdef0123456789abcdef01234567",
          type: "github"
        },
        original: {
          dir: "Linux/NixOS/presets/personal",
          owner: "TakuyaYagam1",
          ref: "dev",
          repo: "MySetup",
          type: "github"
        }
      },
      root: { inputs: { mysetup: "mysetup" } }
    },
    root: "root",
    version: 7
  }
' > "$offline_fixture/flake.lock"
offline_node_before="$(jq -c '.nodes.mysetup' "$offline_fixture/flake.lock")"
python3 "$helper" migrate "$offline_fixture"
test "$(printf '%s' "$offline_node_before" | jq -c '.locked.repo = "wahrwelt" | .original.repo = "wahrwelt"')" = \
    "$(jq -c '.nodes.wahrwelt' "$offline_fixture/flake.lock")"
offline_lock_before="$(sha256sum "$offline_fixture/flake.lock")"
if ! offline_metadata="$(
    nix flake metadata --json --offline --no-write-lock-file "path:$offline_fixture" 2>&1
)"; then
    printf 'FAIL migrated v1 lock does not resolve offline\n%s\n' "$offline_metadata" >&2
    exit 1
fi
if printf '%s\n' "$offline_metadata" |
    grep -Eiq 'warning:|fetching|updating|lock file.*(change|update|write)'; then
    printf 'FAIL migrated v1 lock requested a fetch or lock update\n%s\n' "$offline_metadata" >&2
    exit 1
fi
test "$offline_lock_before" = "$(sha256sum "$offline_fixture/flake.lock")"

canonical="$test_root/canonical/etc/nixos"
canonical_external="$test_root/canonical/etc/wahrwelt/hashed-password"
mkdir -p "$canonical"
printf '%s' "$v2_password_flake" > "$canonical/flake.nix"
printf '%s\n' '{ custom.mysetup = "supported alias"; }' > "$canonical/configuration.nix"
printf '%s\n' '{ ... }: { }' > "$canonical/hardware-configuration.nix"
printf '%s\n' '{ host.hostname = "NixOS"; }' > "$canonical/host-vars.nix"
printf '%s\n' '{ }' > "$canonical/home.nix"
printf '%s\n' '{
  "nodes": {
    "root": { "inputs": { "wahrwelt": "wahrwelt" } },
    "wahrwelt": {
      "locked": {
        "dir": "Linux/NixOS/presets/personal",
        "lastModified": 1234567890,
        "narHash": "sha256-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC=",
        "owner": "TakuyaYagam1",
        "repo": "wahrwelt",
        "rev": "0123456789abcdef0123456789abcdef01234567",
        "type": "github"
      },
      "original": {
        "dir": "Linux/NixOS/presets/personal",
        "owner": "TakuyaYagam1",
        "ref": "main",
        "repo": "wahrwelt",
        "type": "github"
      }
    }
  },
  "root": "root",
  "version": 7
}' > "$canonical/flake.lock"
write_password_module "$canonical/hosts/NixOS/hashed-password.nix" wahrwelt "$test_hash"
canonical_lock_before="$(sha256sum "$canonical/flake.lock")"
test "$(python3 "$helper" classify "$canonical")" = v2-password
canonical_publish_output="$(python3 "$helper" publish-password "$canonical" "$canonical_external" 2>&1)"
test -z "$canonical_publish_output"
canonical_migrate_output="$(python3 "$helper" migrate "$canonical" "$canonical_external" 2>&1)"
test -z "$canonical_migrate_output"
python3 "$helper" validate "$canonical" "$canonical_external"
test "$canonical_lock_before" = "$(sha256sum "$canonical/flake.lock")"
test ! -e "$canonical/hosts/NixOS/hashed-password.nix"
test -f "$canonical/.wahrwelt-password-hash-enabled"
grep -Fq '# supported compatibility alias in documentation: mysetup' "$canonical/flake.nix"
cmp -s "$test_root/expected-hash" "$canonical_external"

no_hash="$test_root/no-hash/etc/nixos"
no_hash_external="$test_root/no-hash/etc/wahrwelt/hashed-password"
mkdir -p "$no_hash"
printf '%s' "$v2_password_flake" > "$no_hash/flake.nix"
cp "$canonical/flake.lock" "$no_hash/flake.lock"
test "$(python3 "$helper" classify "$no_hash")" = v2-password
test -z "$(python3 "$helper" publish-password "$no_hash" "$no_hash_external" 2>&1)"
test ! -e "$no_hash_external"
python3 "$helper" migrate "$no_hash" "$no_hash_external"
python3 "$helper" validate "$no_hash" "$no_hash_external"
test ! -e "$no_hash/.wahrwelt-password-hash-enabled"

unknown_module="$test_root/unknown-module/etc/nixos"
unknown_external="$test_root/unknown-module/etc/wahrwelt/hashed-password"
mkdir -p "$unknown_module"
printf '%s' "$v2_password_flake" > "$unknown_module/flake.nix"
printf '%s\n' 'user-owned unknown module' > "$unknown_module/hashed-password.nix"
chmod 0600 "$unknown_module/hashed-password.nix"
unknown_before="$(sha256sum "$unknown_module/hashed-password.nix")"
expect_password_failure "$unknown_module" "$unknown_external" "an unknown password module"
test "$unknown_before" = "$(sha256sum "$unknown_module/hashed-password.nix")"
test ! -e "$unknown_external"

symlink_module="$test_root/symlink-module/etc/nixos"
symlink_external="$test_root/symlink-module/etc/wahrwelt/hashed-password"
mkdir -p "$symlink_module"
printf '%s' "$v2_password_flake" > "$symlink_module/flake.nix"
write_password_module "$test_root/symlink-module/outside-password.nix" wahrwelt "$test_hash"
ln -s "$test_root/symlink-module/outside-password.nix" "$symlink_module/hashed-password.nix"
outside_before="$(sha256sum "$test_root/symlink-module/outside-password.nix")"
expect_password_failure "$symlink_module" "$symlink_external" "a symlinked password module"
test "$outside_before" = "$(sha256sum "$test_root/symlink-module/outside-password.nix")"
test -L "$symlink_module/hashed-password.nix"

hardlink_module="$test_root/hardlink-module/etc/nixos"
hardlink_external="$test_root/hardlink-module/etc/wahrwelt/hashed-password"
mkdir -p "$hardlink_module"
printf '%s' "$v2_password_flake" > "$hardlink_module/flake.nix"
write_password_module "$test_root/hardlink-module/outside-password.nix" wahrwelt "$test_hash"
ln "$test_root/hardlink-module/outside-password.nix" "$hardlink_module/hashed-password.nix"
expect_password_failure "$hardlink_module" "$hardlink_external" "a hardlinked password module"
test "$(stat -c %h "$hardlink_module/hashed-password.nix")" = 2

dual_module="$test_root/dual-module/etc/nixos"
dual_external="$test_root/dual-module/etc/wahrwelt/hashed-password"
mkdir -p "$dual_module"
printf '%s' "$v2_password_flake" > "$dual_module/flake.nix"
write_password_module "$dual_module/hashed-password.nix" wahrwelt "$test_hash"
write_password_module "$dual_module/hosts/NixOS/hashed-password.nix" wahrwelt "$test_hash"
expect_password_failure "$dual_module" "$dual_external" "multiple password module sources"
test -f "$dual_module/hashed-password.nix"
test -f "$dual_module/hosts/NixOS/hashed-password.nix"

external_collision="$test_root/external-collision/etc/nixos"
collision_external="$test_root/external-collision/etc/wahrwelt/hashed-password"
mkdir -p "$external_collision" "$(dirname "$collision_external")"
chmod 0700 "$(dirname "$collision_external")"
printf '%s' "$v2_password_flake" > "$external_collision/flake.nix"
write_password_module "$external_collision/hashed-password.nix" wahrwelt "$test_hash"
printf '%s\n' "$other_hash" > "$collision_external"
chmod 0600 "$collision_external"
collision_before="$(sha256sum "$collision_external")"
expect_password_failure "$external_collision" "$collision_external" "a conflicting external password hash"
test "$collision_before" = "$(sha256sum "$collision_external")"
test -f "$external_collision/hashed-password.nix"

external_symlink="$test_root/external-symlink/etc/nixos"
symlink_external="$test_root/external-symlink/etc/wahrwelt/hashed-password"
mkdir -p "$external_symlink" "$(dirname "$symlink_external")"
chmod 0700 "$(dirname "$symlink_external")"
printf '%s' "$v2_password_flake" > "$external_symlink/flake.nix"
write_password_module "$external_symlink/hashed-password.nix" wahrwelt "$test_hash"
printf '%s\n' "$test_hash" > "$test_root/external-symlink/outside-hash"
chmod 0600 "$test_root/external-symlink/outside-hash"
ln -s "$test_root/external-symlink/outside-hash" "$symlink_external"
outside_external_before="$(sha256sum "$test_root/external-symlink/outside-hash")"
expect_password_failure "$external_symlink" "$symlink_external" "a symlinked external password target"
test "$outside_external_before" = "$(sha256sum "$test_root/external-symlink/outside-hash")"
test -L "$symlink_external"

external_hardlink="$test_root/external-hardlink/etc/nixos"
hardlink_external="$test_root/external-hardlink/etc/wahrwelt/hashed-password"
mkdir -p "$external_hardlink" "$(dirname "$hardlink_external")"
chmod 0700 "$(dirname "$hardlink_external")"
printf '%s' "$v2_password_flake" > "$external_hardlink/flake.nix"
write_password_module "$external_hardlink/hashed-password.nix" wahrwelt "$test_hash"
printf '%s\n' "$test_hash" > "$test_root/external-hardlink/outside-hash"
chmod 0600 "$test_root/external-hardlink/outside-hash"
ln "$test_root/external-hardlink/outside-hash" "$hardlink_external"
expect_password_failure "$external_hardlink" "$hardlink_external" "a hardlinked external password target"
test "$(stat -c %h "$hardlink_external")" = 2

marker_collision="$test_root/marker-collision/etc/nixos"
marker_external="$test_root/marker-collision/etc/wahrwelt/hashed-password"
mkdir -p "$marker_collision"
printf '%s' "$v2_password_flake" > "$marker_collision/flake.nix"
write_password_module "$marker_collision/hashed-password.nix" wahrwelt "$test_hash"
printf '%s\n' 'user-owned marker' > "$marker_collision/.wahrwelt-password-hash-enabled"
marker_before="$(sha256sum "$marker_collision/.wahrwelt-password-hash-enabled")"
expect_password_failure "$marker_collision" "$marker_external" "a legacy marker collision"
test "$marker_before" = "$(sha256sum "$marker_collision/.wahrwelt-password-hash-enabled")"
test -f "$marker_collision/hashed-password.nix"
test ! -e "$marker_external"

unrecognized="$test_root/unrecognized"
mkdir -p "$unrecognized"
printf '%s\n' '# Generated by MySetup installer.' '{ user.mysetup = "owned by user"; }' > "$unrecognized/flake.nix"
unrecognized_before="$(sha256sum "$unrecognized/flake.nix")"
test "$(python3 "$helper" classify "$unrecognized")" = unrecognized
if python3 "$helper" migrate "$unrecognized" >/dev/null 2>&1; then
    printf 'FAIL v1_to_v2 accepted an arbitrary user module\n' >&2
    exit 1
fi
test "$unrecognized_before" = "$(sha256sum "$unrecognized/flake.nix")"

unknown_url="$test_root/unknown-url"
mkdir -p "$unknown_url"
printf '%s' "$v1_flake" |
    sed 's|presets/personal"|presets/personal-user-owned"|' > "$unknown_url/flake.nix"
unknown_url_before="$(sha256sum "$unknown_url/flake.nix")"
test "$(python3 "$helper" classify "$unknown_url")" = unrecognized
if python3 "$helper" migrate "$unknown_url" >/dev/null 2>&1; then
    printf 'FAIL v1_to_v2 accepted a generated-looking wrapper with an unknown URL\n' >&2
    exit 1
fi
test "$unknown_url_before" = "$(sha256sum "$unknown_url/flake.nix")"

symlink_fixture="$test_root/symlink"
mkdir -p "$symlink_fixture"
printf '%s' "$v1_flake" > "$test_root/user-wrapper.nix"
ln -s "$test_root/user-wrapper.nix" "$symlink_fixture/flake.nix"
symlink_before="$(sha256sum "$test_root/user-wrapper.nix")"
test "$(python3 "$helper" classify "$symlink_fixture")" = unrecognized
if python3 "$helper" migrate "$symlink_fixture" >/dev/null 2>&1; then
    printf 'FAIL v1_to_v2 accepted an unowned flake symlink\n' >&2
    exit 1
fi
test "$symlink_before" = "$(sha256sum "$test_root/user-wrapper.nix")"

printf 'OK nix brand migration v1_to_v2\n'
