# ## Shell keybinds: Caelestia
# Launcher
bindi = Super, Super_L, global, caelestia:launcher
bindin = Super, catchall, global, caelestia:launcherInterrupt
bindin = Super, mouse:272, global, caelestia:launcherInterrupt
bindin = Super, mouse:273, global, caelestia:launcherInterrupt
bindin = Super, mouse:274, global, caelestia:launcherInterrupt
bindin = Super, mouse:275, global, caelestia:launcherInterrupt
bindin = Super, mouse:276, global, caelestia:launcherInterrupt
bindin = Super, mouse:277, global, caelestia:launcherInterrupt
bindin = Super, mouse_up, global, caelestia:launcherInterrupt
bindin = Super, mouse_down, global, caelestia:launcherInterrupt

# Misc
bind = $kbSession, global, caelestia:session
bind = $kbShowSidebar, global, caelestia:sidebar
bindl = $kbClearNotifs, global, caelestia:clearNotifs
bind = $kbShowPanels, global, caelestia:showall
bind = $kbLock, global, caelestia:lock
bind = Ctrl+Shift, W, exec, $hypr/scripts/shell-selector.sh toggle

# Restore lock
bindl = $kbRestoreLock, exec, $hypr/scripts/start-shell.sh caelestia
bindl = $kbRestoreLock, global, caelestia:lock

# Brightness
bindl = , XF86MonBrightnessUp, global, caelestia:brightnessUp
bindl = , XF86MonBrightnessDown, global, caelestia:brightnessDown

# Media
bindl = Ctrl+Super, Space, global, caelestia:mediaToggle
bindl = , XF86AudioPlay, global, caelestia:mediaToggle
bindl = , XF86AudioPause, global, caelestia:mediaToggle
bindl = Ctrl+Super, Equal, global, caelestia:mediaNext
bindl = , XF86AudioNext, global, caelestia:mediaNext
bindl = Ctrl+Super, Minus, global, caelestia:mediaPrev
bindl = , XF86AudioPrev, global, caelestia:mediaPrev
bindl = , XF86AudioStop, global, caelestia:mediaStop

# Kill/restart
bindr = Ctrl+Super+Shift, R, exec, qs -c caelestia kill
bindr = Ctrl+Super+Alt, R, exec, qs -c caelestia kill; sleep .1; $hypr/scripts/start-shell.sh caelestia

# Window actions
bind = $kbWindowPip, exec, caelestia resizer pip  # Move window to picture-in-picture mode

# Apps
bind = $kbTerminal, exec, app2unit -- $terminal
bind = $kbZen, exec, app2unit -- $zen
bind = $kbCursor, exec, app2unit -- $cursor
bind = $kbVscode, exec, app2unit -- $vscode
bind = $kbGoland, exec, app2unit -- $goland
bind = $kbDatagrip, exec, app2unit -- $datagrip
bind = $kbAntigravity, exec, app2unit -- $antigravity
bind = $kbAmneziaVPN, exec, app2unit -- $amneziaVPN
bind = $kbv2rayN, exec, app2unit -- $v2rayN
bind = $kbVesktop, exec, app2unit -- $vesktop
bind = $kbSpotify, exec, $hypr/scripts/spotify-toggle.sh
bind = $kbTelegram, exec, app2unit -- $telegram
bind = $kbBtop, exec, app2unit -- $btop
bind = $kbFileExplorer, exec, app2unit -- $fileExplorer
bind = Super+Alt, E, exec, app2unit -- nemo
bind = Ctrl+Alt, Escape, exec, app2unit -- qps
bind = Ctrl+Alt, V, exec, app2unit -- pavucontrol

# Recording
bindl = Super, S, exec, $hypr/scripts/screenshot.sh full  # Full screen capture > file + clipboard
bind = Super+Shift, S, exec, $hypr/scripts/screenshot.sh region  # Capture region > file + clipboard
bind = Super+Shift+Alt, S, exec, $hypr/scripts/screenshot.sh edit  # Capture region > file + editor
bind = Super+Alt, R, exec, caelestia record -s  # Record screen with sound
bind = Ctrl+Alt, R, exec, caelestia record  # Record screen
bind = Super+Shift+Alt, R, exec, caelestia record -r  # Record region
bind = Super, C, exec, hyprpicker -a  # Colour picker

# Clipboard and emoji picker
bind = Super, V, exec, pkill fuzzel || caelestia clipboard
bind = Super+Alt, V, exec, pkill fuzzel || caelestia clipboard -d
bind = Super, Period, exec, pkill fuzzel || caelestia emoji -p
