bind = $kbSession, global, caelestia:session
bind = $kbShowSidebar, global, caelestia:sidebar
bindl = $kbClearNotifs, global, caelestia:clearNotifs
bind = $kbShowPanels, global, caelestia:showall
bind = $kbLock, global, caelestia:lock

bindl = $kbRestoreLock, exec, $hypr/scripts/restore-lock.sh caelestia

bindl = , XF86MonBrightnessUp, global, caelestia:brightnessUp
bindl = , XF86MonBrightnessDown, global, caelestia:brightnessDown

bindl = Ctrl+Super, Space, global, caelestia:mediaToggle
bindl = , XF86AudioPlay, global, caelestia:mediaToggle
bindl = , XF86AudioPause, global, caelestia:mediaToggle
bindl = Ctrl+Super, Equal, global, caelestia:mediaNext
bindl = , XF86AudioNext, global, caelestia:mediaNext
bindl = Ctrl+Super, Minus, global, caelestia:mediaPrev
bindl = , XF86AudioPrev, global, caelestia:mediaPrev
bindl = , XF86AudioStop, global, caelestia:mediaStop

bindr = Ctrl+Super+Shift, R, exec, qs -c caelestia kill
bindr = Ctrl+Super+Alt, R, exec, qs -c caelestia kill; sleep .1; $hypr/scripts/start-shell.sh caelestia

bind = $kbWindowPip, exec, caelestia resizer pip

source = $hypr/shell-common-keybinds.conf

bind = Super+Alt, R, exec, caelestia record -s
bind = Ctrl+Alt, R, exec, caelestia record
bind = Super+Shift+Alt, R, exec, caelestia record -r

bind = Super, V, exec, pkill fuzzel || caelestia clipboard
bind = Super+Alt, V, exec, pkill fuzzel || caelestia clipboard -d
bind = Super, Period, exec, pkill fuzzel || caelestia emoji -p
