local mysetup = require("lib.mysetup")

require("hyprland.env")
require("hyprland.general")
require("hyprland.input")
mysetup.optional_require("mysetup.local")
require("hyprland.misc")
require("hyprland.animations")
require("hyprland.decoration")
require("hyprland.group")
require("hyprland.execs")
require("hyprland.rules")
require("hyprland.gestures")
require("hyprland.scrolling")
require("hyprland.keybinds")
require("vm-keybinds")
