{
  config,
  wahrweltLib,
  pkgs,
  ...
}:

{
  config = wahrweltLib.mkIfPresetOrMore "developer" config.wahrwelt {
    programs.nix-ld = {
      enable = true;
      libraries = with pkgs; [
        stdenv.cc.cc.lib
        glibc
        zlib
        zstd
        xz
        bzip2
        libffi
        libuuid
        libxml2
        libxslt
        libgcrypt
        openssl
        nss
        nspr
        icu
        libuv
        ncurses
        readline
        sqlite
        libpng
        libGL
        libGLU
        libdrm
        libepoxy
        libxkbcommon
        libxkbfile
        libx11
        libxext
        libxrender
        libxrandr
        libxcursor
        libxi
        libxfixes
        libxcomposite
        xcbutil
        xcbutilxrm
        libxcb-keysyms
        libxcb-wm
        libxcb-render-util
        libxcb-image
        libxcb-cursor
        pcre
        pulseaudio
        dbus
        expat
        libbsd
        glib
        qt6.qtbase
        qt6.qtwayland
        qt6.qtmultimedia
        qt6.qttools
        qt6.qtdeclarative
      ];
    };
  };
}
