# ## Shell keybinds: Noctalia
$noctalia = noctalia-shell ipc call

# Launcher
bindi = Super, Super_L, exec, $hypr/scripts/noctalia-launcher.sh press
bindr = Super, Super_L, exec, $hypr/scripts/noctalia-launcher.sh release
bindin = Super, catchall, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse:272, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse:273, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse:274, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse:275, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse:276, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse:277, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse_up, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse_down, exec, $hypr/scripts/noctalia-launcher.sh interrupt

# Panels
bind = $kbSession, exec, $noctalia sessionMenu toggle
bind = $kbShowSidebar, exec, $noctalia controlCenter toggle
bindl = $kbClearNotifs, exec, $noctalia notifications clear
bind = $kbShowPanels, exec, $noctalia settings toggle
bind = $kbLock, exec, $noctalia lockScreen lock
bind = Ctrl+Shift, W, exec, $hypr/scripts/shell-selector.sh toggle

# Restore lock
bindl = $kbRestoreLock, exec, $hypr/scripts/start-shell.sh noctalia
bindl = $kbRestoreLock, exec, $noctalia lockScreen lock

# Brightness
bindl = , XF86MonBrightnessUp, exec, $noctalia brightness increase
bindl = , XF86MonBrightnessDown, exec, $noctalia brightness decrease

# Media
bindl = Ctrl+Super, Space, exec, $noctalia media playPause
bindl = , XF86AudioPlay, exec, $noctalia media playPause
bindl = , XF86AudioPause, exec, $noctalia media playPause
bindl = Ctrl+Super, Equal, exec, $noctalia media next
bindl = , XF86AudioNext, exec, $noctalia media next
bindl = Ctrl+Super, Minus, exec, $noctalia media previous
bindl = , XF86AudioPrev, exec, $noctalia media previous
bindl = , XF86AudioStop, exec, $noctalia media stop

# Apps
bind = $kbTerminal, exec, app2unit -- $terminal
bind = $kbZen, exec, app2unit -- $zen
bind = $kbCursor, exec, app2unit -- $cursor
bind = $kbVscode, exec, app2unit -- $vscode
bind = $kbGoland, exec, app2unit -- $goland
bind = $kbDatagrip, exec, app2unit -- $datagrip
bind = $kbAntigravity, exec, app2unit -- $antigravity
bind = $kbAmneziaVPN, exec, app2unit -- $amneziaVPN
bind = $kbv2rayN, exec, app2unit -- $v2rayN
bind = $kbVesktop, exec, app2unit -- $vesktop
bind = $kbSpotify, exec, $hypr/scripts/spotify-toggle.sh
bind = $kbTelegram, exec, app2unit -- $telegram
bind = $kbBtop, exec, app2unit -- $btop
bind = $kbFileExplorer, exec, app2unit -- $fileExplorer
bind = Super+Alt, E, exec, app2unit -- nemo
bind = Ctrl+Alt, Escape, exec, app2unit -- qps
bind = Ctrl+Alt, V, exec, app2unit -- pavucontrol

# Utilities
bindl = Super, S, exec, $hypr/scripts/screenshot.sh full  # Full screen capture > file + clipboard
bind = Super+Shift, S, exec, $hypr/scripts/screenshot.sh region  # Capture region > file + clipboard
bind = Super+Shift+Alt, S, exec, $hypr/scripts/screenshot.sh edit  # Capture region > file + editor
bind = $kbRecord, exec, $hypr/scripts/record-toggle.sh  # Toggle full screen recording with desktop audio
bind = Super, C, exec, hyprpicker -a  # Colour picker

# Launcher modes
bind = Super, V, exec, $noctalia launcher clipboard
bind = Super+Alt, V, exec, $noctalia launcher clipboard
bind = Super, Period, exec, $noctalia launcher emoji
