$noctalia = noctalia-shell ipc call

bind = $kbSession, exec, $noctalia sessionMenu toggle
bind = $kbShowSidebar, exec, $noctalia controlCenter toggle
bindl = $kbClearNotifs, exec, $noctalia notifications clear
bind = $kbShowPanels, exec, $noctalia settings toggle
bind = $kbLock, exec, $noctalia lockScreen lock

bindl = $kbRestoreLock, exec, $hypr/scripts/restore-lock.sh noctalia

bindl = , XF86MonBrightnessUp, exec, $noctalia brightness increase
bindl = , XF86MonBrightnessDown, exec, $noctalia brightness decrease

bindl = Ctrl+Super, Space, exec, $noctalia media playPause
bindl = , XF86AudioPlay, exec, $noctalia media playPause
bindl = , XF86AudioPause, exec, $noctalia media playPause
bindl = Ctrl+Super, Equal, exec, $noctalia media next
bindl = , XF86AudioNext, exec, $noctalia media next
bindl = Ctrl+Super, Minus, exec, $noctalia media previous
bindl = , XF86AudioPrev, exec, $noctalia media previous
bindl = , XF86AudioStop, exec, $noctalia media stop

source = $hypr/shell-common-keybinds.conf

bind = $kbRecord, exec, $hypr/scripts/record-toggle.sh

bind = Super, V, exec, $noctalia launcher clipboard
bind = Super+Alt, V, exec, $noctalia launcher clipboard
bind = Super, Period, exec, $noctalia launcher emoji
