bindi = Super, Super_L, exec, $hypr/scripts/noctalia-launcher.sh press
bindr = Super, Super_L, exec, $hypr/scripts/noctalia-launcher.sh release
bindin = Super, catchall, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse:272, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse:273, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse:274, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse:275, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse:276, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse:277, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse_up, exec, $hypr/scripts/noctalia-launcher.sh interrupt
bindin = Super, mouse_down, exec, $hypr/scripts/noctalia-launcher.sh interrupt
