{
  config,
  inputs,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.wahrwelt;
  destination = cfg.host.configDirectory;
  username = cfg.user.username;
  hostname = cfg.host.hostname;
  v1ToV2NamespaceSource = pkgs.writeText "wahrwelt-v1-to-v2-user-namespace.py" (
    builtins.readFile ./migrations/v1_to_v2/user-namespace.py
  );
  v1ToV2BrandSource = pkgs.writeText "wahrwelt-v1-to-v2-brand.py" (
    builtins.readFile ./migrations/v1_to_v2/brand.py
  );
  v1ToV2MigrationTool = pkgs.writeShellApplication {
    name = "wahrwelt-v1-to-v2-migration";
    runtimeInputs = with pkgs; [
      coreutils
      findutils
      gnugrep
      gnutar
      nix
      rsync
      util-linux
    ];
    text = ''
      set -euo pipefail

      destination=${lib.escapeShellArg destination}
      hostname=${lib.escapeShellArg hostname}
      namespace_python=${lib.escapeShellArg "${pkgs.python3}/bin/python3"}
      namespace_helper=${lib.escapeShellArg v1ToV2NamespaceSource}
      brand_helper=${lib.escapeShellArg v1ToV2BrandSource}
      fs_helper=${lib.escapeShellArg "${inputs.wahrwelt.packages.${pkgs.stdenv.hostPlatform.system}.wahrwelt}/bin/wahrwelt-fs-helper"}
      password_hash_target=${lib.escapeShellArg "/etc/wahrwelt/hashed-password"}
      work_root="''${WAHRWELT_MIGRATION_WORK_ROOT:-/var/lib/wahrwelt/migration}"

      v1_evidence=0
      for v1_path in \
        "$destination/private" \
        "$destination/wahrwelt/state.json" \
        "$destination/mysetup/state.json"; do
        if [ -e "$v1_path" ] || [ -L "$v1_path" ]; then
          v1_evidence=1
          break
        fi
      done
      password_evidence="$(
        "$namespace_python" "$brand_helper" \
          password-evidence "$destination" "$password_hash_target"
      )"
      case "$password_evidence" in
        legacy) v1_evidence=1 ;;
        absent | completed | unrecognized) ;;
        *)
          echo "Wahrwelt migration: invalid v1_to_v2 password evidence: $password_evidence" >&2
          exit 1
          ;;
      esac
      if [ "$v1_evidence" -eq 0 ] &&
        [ -f "$destination/flake.nix" ] &&
        grep -Fq '# Generated by MySetup installer.' "$destination/flake.nix"; then
        v1_evidence=1
      fi
      if [ "$v1_evidence" -eq 0 ]; then
        exit 0
      fi

      validate_work_directory() {
        local path="$1"
        local owner mode resolved

        if [ -L "$path" ] || [ ! -d "$path" ]; then
          echo "Wahrwelt migration ownership collision: $path must be an ordinary directory" >&2
          exit 1
        fi
        resolved="$(realpath -e -- "$path")"
        if [ "$resolved" != "$path" ]; then
          echo "Wahrwelt migration ownership collision: $path must not traverse symlinks" >&2
          exit 1
        fi
        owner="$(stat -c %u -- "$path")"
        mode="$(stat -c %a -- "$path")"
        if [ "$owner" != 0 ] || [ "$((8#$mode & 0022))" -ne 0 ]; then
          echo "Wahrwelt migration ownership collision: $path must be root-owned and not group/world-writable" >&2
          exit 1
        fi
      }

      case "$work_root" in
        /*) ;;
        *)
          echo "Wahrwelt migration ownership collision: work root must be absolute: $work_root" >&2
          exit 1
          ;;
      esac
      normalized_work_root="$(realpath -m -- "$work_root")"
      if [ "$normalized_work_root" = / ] || [ "$normalized_work_root" != "$work_root" ]; then
        echo "Wahrwelt migration ownership collision: unsafe work root: $work_root" >&2
        exit 1
      fi

      trusted_ancestor="$work_root"
      while [ ! -e "$trusted_ancestor" ] && [ ! -L "$trusted_ancestor" ]; do
        next_ancestor="$(dirname -- "$trusted_ancestor")"
        if [ "$next_ancestor" = "$trusted_ancestor" ]; then
          echo "Wahrwelt migration ownership collision: cannot resolve work root: $work_root" >&2
          exit 1
        fi
        trusted_ancestor="$next_ancestor"
      done
      while :; do
        validate_work_directory "$trusted_ancestor"
        [ "$trusted_ancestor" != / ] || break
        trusted_ancestor="$(dirname -- "$trusted_ancestor")"
      done

      umask 077
      mkdir -p -- "$work_root"
      validate_work_directory "$work_root"
      work_root_id="$(stat -c '%d:%i' -- "$work_root")"
      work_root_owner="$(stat -c '%u' -- "$work_root")"
      exec 9<"$work_root"
      if [ "$(stat -Lc '%d:%i' -- /proc/self/fd/9)" != "$work_root_id" ]; then
        echo "Wahrwelt migration ownership collision: work root changed while opening: $work_root" >&2
        exit 1
      fi
      flock 9
      work_root_fd="/proc/self/fd/9"

      completion_status="$(
        "$namespace_python" "$namespace_helper" "completion-status" "$work_root_fd"
      )"
      case "$completion_status" in
        absent) ;;
        complete)
          echo "Wahrwelt migration ownership collision: v1 evidence remains after the recorded v1_to_v2 completion" >&2
          exit 1
          ;;
        *)
          echo "Wahrwelt migration ownership collision: invalid completion status: $completion_status" >&2
          exit 1
          ;;
      esac

      brand_kind="$("$namespace_python" "$brand_helper" classify "$destination")"
      case "$brand_kind" in
        v1)
          brand_migration=1
          password_migration=0
          ;;
        v1-password)
          brand_migration=1
          password_migration=1
          ;;
        v2)
          brand_migration=0
          password_migration=0
          ;;
        v2-password)
          brand_migration=0
          password_migration=1
          ;;
        unrecognized)
          echo "Wahrwelt migration: refusing to rewrite an unrecognized $destination/flake.nix" >&2
          exit 1
          ;;
        *)
          echo "Wahrwelt migration: invalid v1_to_v2 classifier result: $brand_kind" >&2
          exit 1
          ;;
      esac

      namespace_migration=0
      if "$namespace_python" "$namespace_helper" "needs-migration" "$destination"; then
        namespace_migration=1
      else
        namespace_status=$?
        if [ "$namespace_status" -ne 1 ]; then
          exit "$namespace_status"
        fi
      fi

      if [ "$namespace_migration" -eq 0 ] &&
        [ "$brand_migration" -eq 0 ] &&
        [ "$password_migration" -eq 0 ]; then
        echo "Wahrwelt migration ownership collision: v1 evidence was not recognized by the v1_to_v2 migration" >&2
        exit 1
      fi

      destination_parent="$(dirname -- "$destination")"
      destination_parent_id="$(stat -c '%d:%i' -- "$destination_parent")"
      exec {destination_parent_fd}<"$destination_parent"
      destination_parent_pinned="/proc/self/fd/$destination_parent_fd"
      if [ "$(stat -Lc '%d:%i' -- "$destination_parent_pinned")" != "$destination_parent_id" ]; then
        echo "Wahrwelt migration ownership collision: destination parent changed while opening: $destination_parent" >&2
        exit 1
      fi

      destination_name="$(basename -- "$destination")"
      case "$destination_name" in
        "" | . | .. | */*)
          echo "Wahrwelt migration ownership collision: invalid destination name: $destination_name" >&2
          exit 1
          ;;
      esac
      if [ -L "$destination_parent_pinned/$destination_name" ] ||
        [ ! -d "$destination_parent_pinned/$destination_name" ]; then
        echo "Wahrwelt migration ownership collision: $destination must be an ordinary directory" >&2
        exit 1
      fi
      destination_id="$(stat -c '%d:%i' -- "$destination_parent_pinned/$destination_name")"
      exec {destination_fd}<"$destination_parent_pinned/$destination_name"
      destination_pinned="/proc/self/fd/$destination_fd"
      if [ "$(stat -c '%d:%i' -- "$destination_parent_pinned/$destination_name")" != "$destination_id" ] ||
        [ "$(stat -Lc '%d:%i' -- "$destination_pinned")" != "$destination_id" ] ||
        [ ! -d "$destination_pinned" ]; then
        echo "Wahrwelt migration ownership collision: destination changed while opening: $destination" >&2
        exit 1
      fi

      if [ "$password_migration" -eq 1 ]; then
        "$namespace_python" "$brand_helper" \
          publish-password "$destination" "$password_hash_target"
      fi

      create_owned_temp() {
        local kind="$1"
        local parent_pinned="$2"
        local prefix="$3"
        local created

        created="$(
          "$namespace_python" "$namespace_helper" \
            "create-owned-temp" "$kind" "$parent_pinned" "$prefix"
        )"
        IFS=$'\t' read -r created_name created_token <<<"$created"
        case "$created_name" in
          "" | . | .. | */*)
            echo "Wahrwelt migration ownership collision: creator returned an invalid name: $created_name" >&2
            exit 1
            ;;
        esac
        case "$created_token" in
          *:*) ;;
          *)
            echo "Wahrwelt migration ownership collision: creator returned an invalid identity: $created_token" >&2
            exit 1
            ;;
        esac
      }

      creation_barrier() {
        local label="$1"
        local name="$2"
        local identity="$3"
        local ready_name="$4"
        local continue_name="$5"
        local ready_fd continue_fd release

        ready_fd="$(printenv "$ready_name" 2>/dev/null || true)"
        continue_fd="$(printenv "$continue_name" 2>/dev/null || true)"
        if [ -z "$ready_fd" ] && [ -z "$continue_fd" ]; then
          return
        fi
        if [ -z "$ready_fd" ] || [ -z "$continue_fd" ]; then
          echo "Wahrwelt migration ownership collision: incomplete $label creation barrier" >&2
          exit 1
        fi
        printf '%s\t%s\t%s\n' "$label" "$name" "$identity" >&"$ready_fd"
        if ! IFS= read -r -N 1 -u "$continue_fd" release || [ "$release" != 1 ]; then
          echo "Wahrwelt migration ownership collision: $label creation barrier was not released" >&2
          exit 1
        fi
      }

      report_created_recovery() {
        local label="$1"
        local parent_pinned="$2"
        local parent_display="$3"
        local name="$4"
        local identity="$5"
        local owner_fd="''${6:-}"
        local retained="" visible_id found

        if [ -n "$owner_fd" ]; then
          retained="$(readlink -- "/proc/self/fd/$owner_fd" 2>/dev/null || true)"
        fi
        if [ -z "$retained" ]; then
          found="$(
            "$namespace_python" "$namespace_helper" \
              "find-owned-temp" "$parent_pinned" "$identity" 2>/dev/null || true
          )"
          if [ -n "$found" ]; then
            retained="$parent_display/$(printf '%s\n' "$found" | head -n 1)"
          fi
        fi
        if [ -n "$retained" ]; then
          echo "Wahrwelt migration $label retained at $retained" >&2
        else
          echo "Wahrwelt migration $label identity $identity has no visible recovery beneath $parent_display" >&2
        fi
        visible_id="$(stat -c '%d:%i' -- "$parent_pinned/$name" 2>/dev/null || true)"
        if [ -n "$visible_id" ] && [ "$visible_id" != "$identity" ]; then
          echo "Wahrwelt migration unknown collision preserved at $parent_display/$name" >&2
        fi
      }

      pin_created_directory() {
        local label="$1"
        local parent_pinned="$2"
        local parent_display="$3"
        local name="$4"
        local identity="$5"
        local output_fd_name="$6"
        local opened_fd visible_id pinned_id

        if ! exec {opened_fd}<"$parent_pinned/$name"; then
          report_created_recovery "$label" "$parent_pinned" "$parent_display" "$name" "$identity"
          return 1
        fi
        visible_id="$(stat -c '%d:%i' -- "$parent_pinned/$name" 2>/dev/null || true)"
        pinned_id="$(stat -Lc '%d:%i' -- "/proc/self/fd/$opened_fd" 2>/dev/null || true)"
        if [ "$visible_id" != "$identity" ] || [ "$pinned_id" != "$identity" ] || [ ! -d "/proc/self/fd/$opened_fd" ]; then
          report_created_recovery "$label" "$parent_pinned" "$parent_display" "$name" "$identity"
          exec {opened_fd}<&-
          return 1
        fi
        printf -v "$output_fd_name" '%s' "$opened_fd"
      }

      pin_created_file() {
        local label="$1"
        local parent_pinned="$2"
        local parent_display="$3"
        local name="$4"
        local identity="$5"
        local output_fd_name="$6"
        local opened_fd visible_id pinned_id

        if ! exec {opened_fd}<>"$parent_pinned/$name"; then
          report_created_recovery "$label" "$parent_pinned" "$parent_display" "$name" "$identity"
          return 1
        fi
        visible_id="$(stat -c '%d:%i' -- "$parent_pinned/$name" 2>/dev/null || true)"
        pinned_id="$(stat -Lc '%d:%i' -- "/proc/self/fd/$opened_fd" 2>/dev/null || true)"
        if [ "$visible_id" != "$identity" ] || [ "$pinned_id" != "$identity" ] || [ ! -f "/proc/self/fd/$opened_fd" ]; then
          report_created_recovery "$label" "$parent_pinned" "$parent_display" "$name" "$identity"
          exec {opened_fd}>&-
          return 1
        fi
        printf -v "$output_fd_name" '%s' "$opened_fd"
      }

      require_visible_created_directory() {
        local label="$1"
        local parent_pinned="$2"
        local parent_display="$3"
        local name="$4"
        local identity="$5"
        local owner_fd="$6"
        local visible_id pinned_id

        visible_id="$(stat -c '%d:%i' -- "$parent_pinned/$name" 2>/dev/null || true)"
        pinned_id="$(stat -Lc '%d:%i' -- "/proc/self/fd/$owner_fd" 2>/dev/null || true)"
        if [ "$visible_id" != "$identity" ] || [ "$pinned_id" != "$identity" ]; then
          report_created_recovery "$label" "$parent_pinned" "$parent_display" "$name" "$identity" "$owner_fd"
          return 1
        fi
      }

      require_private_created_directory() {
        local label="$1"
        local parent_pinned="$2"
        local parent_display="$3"
        local name="$4"
        local identity="$5"
        local owner_fd="$6"
        local visible_metadata pinned_metadata

        if ! require_visible_created_directory \
          "$label" "$parent_pinned" "$parent_display" \
          "$name" "$identity" "$owner_fd"; then
          return 1
        fi
        visible_metadata="$(stat -c '%u:%a' -- "$parent_pinned/$name")"
        pinned_metadata="$(stat -Lc '%u:%a' -- "/proc/self/fd/$owner_fd")"
        if [ "$visible_metadata" != "$work_root_owner:700" ] ||
          [ "$pinned_metadata" != "$work_root_owner:700" ]; then
          echo "Wahrwelt migration ownership collision: $parent_display/$name must remain an owned mode 0700 directory" >&2
          return 1
        fi
      }

      stage_pinned=
      stage_name=
      stage_token=
      stage_fd=
      candidate=
      candidate_pinned=
      candidate_name=
      candidate_token=
      candidate_fd=
      namespace_snapshot=
      namespace_snapshot_name=
      namespace_snapshot_token=
      namespace_snapshot_fd=
      publish_started=0
      cleanup() {
        status=$?
        trap - EXIT
        if [ -n "$stage_token" ]; then
          report_created_recovery \
            "staging directory" "$work_root_fd" "$work_root" \
            "$stage_name" "$stage_token" "$stage_fd"
        fi
        if [ -n "$namespace_snapshot_token" ]; then
          report_created_recovery \
            "namespace snapshot" "$work_root_fd" "$work_root" \
            "$namespace_snapshot_name" "$namespace_snapshot_token" "$namespace_snapshot_fd"
        fi
        if [ -n "$candidate" ] && [ "$status" -eq 0 ] && [ "$publish_started" -eq 1 ]; then
          echo "Wahrwelt migration previous live tree retained at $candidate" >&2
        elif [ -n "$candidate_token" ]; then
          report_created_recovery \
            "recovery candidate" "$destination_parent_pinned" "$destination_parent" \
            "$candidate_name" "$candidate_token" "$candidate_fd"
        fi
        exit "$status"
      }
      trap cleanup EXIT

      create_owned_temp directory "$work_root_fd" staging.
      stage_name="$created_name"
      stage_token="$created_token"
      creation_barrier \
        stage "$stage_name" "$stage_token" \
        WAHRWELT_TEST_MIGRATION_STAGE_CREATED_READY_FD \
        WAHRWELT_TEST_MIGRATION_STAGE_CREATED_CONTINUE_FD
      if ! pin_created_directory \
        "staging directory" "$work_root_fd" "$work_root" \
        "$stage_name" "$stage_token" stage_fd; then
        exit 1
      fi
      stage_pinned="/proc/self/fd/$stage_fd"

      create_owned_temp file "$work_root_fd" namespace.
      namespace_snapshot_name="$created_name"
      namespace_snapshot_token="$created_token"
      creation_barrier \
        snapshot "$namespace_snapshot_name" "$namespace_snapshot_token" \
        WAHRWELT_TEST_MIGRATION_SNAPSHOT_CREATED_READY_FD \
        WAHRWELT_TEST_MIGRATION_SNAPSHOT_CREATED_CONTINUE_FD
      if ! pin_created_file \
        "namespace snapshot" "$work_root_fd" "$work_root" \
        "$namespace_snapshot_name" "$namespace_snapshot_token" namespace_snapshot_fd; then
        exit 1
      fi
      namespace_snapshot="/proc/self/fd/$namespace_snapshot_fd"

      "$namespace_python" "$namespace_helper" "snapshot-live" "$destination" "$namespace_snapshot"
      (
        cd "$destination"
        tar --acls --xattrs --xattrs-include='*' --numeric-owner --sparse -cpf - .
      ) | (
        cd "$stage_pinned"
        tar --acls --xattrs --xattrs-include='*' --numeric-owner \
          --no-overwrite-dir --sparse -xpf -
      )
      if ! require_private_created_directory \
        "staging directory" "$work_root_fd" "$work_root" \
        "$stage_name" "$stage_token" "$stage_fd"; then
        exit 1
      fi

      if [ "$brand_migration" -eq 1 ] || [ "$password_migration" -eq 1 ]; then
        "$namespace_python" "$brand_helper" \
          migrate "$stage_pinned" "$password_hash_target"
      fi

      (
        cd "$stage_pinned"
        "$namespace_python" "$namespace_helper" "migrate-stage" .
      )

      (
        cd "$stage_pinned"
        nix build \
          --offline \
          --no-link \
          --no-write-lock-file \
          "path:.#nixosConfigurations.$hostname.config.system.build.toplevel"
      )

      if ! require_visible_created_directory \
        "staging directory" "$work_root_fd" "$work_root" \
        "$stage_name" "$stage_token" "$stage_fd"; then
        exit 1
      fi

      create_owned_temp \
        directory "$destination_parent_pinned" ".$(basename "$destination").migration."
      candidate_name="$created_name"
      candidate_token="$created_token"
      candidate="$destination_parent/$candidate_name"
      creation_barrier \
        candidate "$candidate_name" "$candidate_token" \
        WAHRWELT_TEST_MIGRATION_CANDIDATE_CREATED_READY_FD \
        WAHRWELT_TEST_MIGRATION_CANDIDATE_CREATED_CONTINUE_FD
      if ! pin_created_directory \
        "recovery candidate" "$destination_parent_pinned" "$destination_parent" \
        "$candidate_name" "$candidate_token" candidate_fd; then
        exit 1
      fi
      candidate_pinned="/proc/self/fd/$candidate_fd"
      if find -H "$candidate_pinned" -mindepth 1 -print -quit | grep -q .; then
        echo "Wahrwelt migration ownership collision: fresh candidate is not empty: $candidate" >&2
        exit 1
      fi
      rsync -aHAX "$stage_pinned/" "$candidate_pinned/"
      # The build stage must stay root-owned and mode 0700, but those are not
      # the ownership semantics of the live configuration root. Copy only the
      # pinned live root metadata after the staged contents are complete.
      (
        cd "$destination_pinned"
        tar --acls --xattrs --xattrs-include='*' --numeric-owner --no-recursion -cpf - .
      ) | (
        cd "$candidate_pinned"
        tar --acls --xattrs --xattrs-include='*' --numeric-owner -xpf -
      )
      (
        cd "$candidate_pinned"
        "$namespace_python" "$namespace_helper" "validate-migrated" .
      )

      if [ "$brand_migration" -eq 1 ] || [ "$password_migration" -eq 1 ]; then
        "$namespace_python" "$brand_helper" \
          validate "$candidate_pinned" "$password_hash_target"
      fi

      if ! require_visible_created_directory \
        "recovery candidate" "$destination_parent_pinned" "$destination_parent" \
        "$candidate_name" "$candidate_token" "$candidate_fd"; then
        exit 1
      fi
      "$namespace_python" "$namespace_helper" "precommit" \
        "$destination" "$candidate" "$namespace_snapshot"
      if ! require_visible_created_directory \
        "recovery candidate" "$destination_parent_pinned" "$destination_parent" \
        "$candidate_name" "$candidate_token" "$candidate_fd"; then
        exit 1
      fi
      publish_started=1
      "$namespace_python" "$namespace_helper" "publish" "$destination" "$candidate" "$namespace_snapshot"

      if ! require_private_created_directory \
        "staging directory" "$work_root_fd" "$work_root" \
        "$stage_name" "$stage_token" "$stage_fd"; then
        exit 1
      fi
      "$fs_helper" remove-migration-temporary \
        --kind staging --name "$stage_name" --expected "$stage_token"
      stage_token=
      exec {stage_fd}<&-
      "$fs_helper" remove-migration-temporary \
        --kind namespace --name "$namespace_snapshot_name" --expected "$namespace_snapshot_token"
      namespace_snapshot_token=
      exec {namespace_snapshot_fd}>&-

      "$namespace_python" "$namespace_helper" \
        "publish-completion" "$work_root_fd"

      echo "Wahrwelt migration completed: $destination"
    '';
  };
in
{
  systemd.services.wahrwelt-v1-to-v2-migration = {
    description = "Migrate a proven Wahrwelt v1 installation to v2";
    wantedBy = [ "multi-user.target" ];
    before = [ "home-manager-${username}.service" ];
    after = [ "nix-daemon.socket" ];
    wants = [ "nix-daemon.socket" ];
    restartTriggers = [
      v1ToV2NamespaceSource
      v1ToV2BrandSource
    ];
    unitConfig = {
      RequiresMountsFor = [
        destination
        cfg.user.homeDirectory
      ];
      ConditionPathExists = [
        "|${destination}/private"
        "|${destination}/wahrwelt/state.json"
        "|${destination}/mysetup/state.json"
        "|${destination}/hashed-password.nix"
        "|${destination}/hosts/NixOS/hashed-password.nix"
      ];
    };
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${v1ToV2MigrationTool}/bin/wahrwelt-v1-to-v2-migration";
      RemainAfterExit = true;
      TimeoutStartSec = "30m";
    };
  };

  systemd.services."home-manager-${username}" = {
    requires = [ "wahrwelt-v1-to-v2-migration.service" ];
    after = [ "wahrwelt-v1-to-v2-migration.service" ];
  };
}
