{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.wahrwelt;
  destination = cfg.host.configDirectory;
  username = cfg.user.username;
  hostname = cfg.host.hostname;
  migrationTool = pkgs.writeShellApplication {
    name = "wahrwelt-brand-migration";
    runtimeInputs = with pkgs; [
      coreutils
      findutils
      gnugrep
      gnused
      jq
      nix
      rsync
      util-linux
    ];
    text = ''
      set -euo pipefail

      destination=${lib.escapeShellArg destination}
      hostname=${lib.escapeShellArg hostname}
      work_root="''${WAHRWELT_MIGRATION_WORK_ROOT:-/var/lib/wahrwelt/migration}"
      marker="$work_root/brand-v1.done"
      lock="$work_root/lock"

      mkdir -p "$work_root"
      exec 9>"$lock"
      flock 9

      has_legacy_paths() {
        [ -e "$destination/mysetup" ] ||
          find "$destination" -path "$destination/secrets" -prune -o -iname '*mysetup*' -print -quit |
            grep -q .
      }

      has_legacy_text() {
        grep -RIl \
          --exclude=hashed-password.nix \
          --exclude-dir=secrets \
          --exclude-dir=.git \
          -i 'mysetup' "$destination" 2>/dev/null |
          grep -q .
      }

      if ! has_legacy_paths && ! has_legacy_text; then
        touch "$marker"
        exit 0
      fi

      if [ ! -f "$destination/flake.nix" ]; then
        echo "Wahrwelt migration: $destination/flake.nix is missing" >&2
        exit 1
      fi
      if ! grep -qE 'Generated by (MySetup|Wahrwelt) installer' "$destination/flake.nix"; then
        echo "Wahrwelt migration: refusing to rewrite an unrecognized $destination/flake.nix" >&2
        exit 1
      fi

      stage="$(mktemp -d "$work_root/staging.XXXXXX")"
      rollback="$(mktemp -d "$work_root/rollback.XXXXXX")"
      committed=0
      cleanup() {
        status=$?
        if [ "$status" -ne 0 ] && [ "$committed" -eq 1 ]; then
          echo "Wahrwelt migration failed after commit; restoring $destination" >&2
          rsync -a --delete "$rollback/" "$destination/" || true
        fi
        rm -rf "$stage"
        if [ "$status" -eq 0 ]; then
          rm -rf "$rollback"
        else
          echo "Wahrwelt migration rollback snapshot retained at $rollback" >&2
        fi
        exit "$status"
      }
      trap cleanup EXIT

      cp -a "$destination/." "$stage/"
      cp -a "$destination/." "$rollback/"

      if [ -e "$stage/mysetup" ]; then
        if [ -e "$stage/wahrwelt" ]; then
          echo "Wahrwelt migration conflict: both state directories exist" >&2
          exit 1
        fi
        mv "$stage/mysetup" "$stage/wahrwelt"
      fi

      while IFS= read -r -d "" old_path; do
        old_name="$(basename "$old_path")"
        new_name="$(printf '%s' "$old_name" | sed \
          -e 's/MYSETUP/WAHRWELT/g' \
          -e 's/MySetup/Wahrwelt/g' \
          -e 's/mysetup/wahrwelt/g')"
        new_path="$(dirname "$old_path")/$new_name"
        if [ "$old_path" = "$new_path" ]; then
          continue
        fi
        if [ -e "$new_path" ] || [ -L "$new_path" ]; then
          echo "Wahrwelt migration conflict: both $old_path and $new_path exist" >&2
          exit 1
        fi
        mv -- "$old_path" "$new_path"
      done < <(
        find "$stage" -depth \
          -path "$stage/secrets" -prune -o \
          -iname '*mysetup*' \
          -print0
      )

      while IFS= read -r -d "" file; do
        sed -i \
          -e 's/MYSETUP/WAHRWELT/g' \
          -e 's/MySetup/Wahrwelt/g' \
          -e 's/mysetup/wahrwelt/g' \
          "$file"
      done < <(
        find "$stage" \
          -path "$stage/secrets" -prune -o \
          -type f \
          ! -name hashed-password.nix \
          \( \
            -name '*.nix' -o \
            -name '*.json' -o \
            -name '*.md' -o \
            -name '*.txt' -o \
            -name '*.lua' -o \
            -name '*.sh' -o \
            -name '*.fish' -o \
            -name '*.js' -o \
            -name flake.lock \
          \) \
          -print0
      )

      jq empty "$stage/flake.lock"
      nix flake update wahrwelt --flake "path:$stage"
      nix build \
        --no-link \
        --no-write-lock-file \
        "path:$stage#nixosConfigurations.$hostname.config.system.build.toplevel"

      rsync -a --delete "$stage/" "$destination/"
      committed=1

      if find "$destination" -path "$destination/secrets" -prune -o -iname '*mysetup*' -print -quit |
        grep -q .; then
        echo "Wahrwelt migration left a legacy path in $destination" >&2
        exit 1
      fi
      if grep -RIl \
        --exclude=hashed-password.nix \
        --exclude-dir=secrets \
        --exclude-dir=.git \
        -i 'mysetup' "$destination" 2>/dev/null |
        grep -q .; then
        echo "Wahrwelt migration left legacy text in $destination" >&2
        exit 1
      fi

      find "$(dirname "$destination")" \
        -maxdepth 1 \
        -mindepth 1 \
        -type d \
        -name "$(basename "$destination").bak.*" \
        -exec rm -rf -- {} +

      touch "$marker"
      echo "Wahrwelt migration completed: $destination"
    '';
  };
in
{
  systemd.services.wahrwelt-brand-migration = {
    description = "Migrate installed configuration to Wahrwelt paths";
    wantedBy = [ "multi-user.target" ];
    before = [ "home-manager-${username}.service" ];
    after = [ "nix-daemon.socket" ];
    wants = [ "nix-daemon.socket" ];
    unitConfig.RequiresMountsFor = [
      destination
      cfg.user.homeDirectory
    ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${migrationTool}/bin/wahrwelt-brand-migration";
      RemainAfterExit = true;
      TimeoutStartSec = "30m";
    };
  };

  systemd.services."home-manager-${username}" = {
    requires = [ "wahrwelt-brand-migration.service" ];
    after = [ "wahrwelt-brand-migration.service" ];
  };
}
