{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.wahrwelt;
  destination = cfg.host.configDirectory;
  username = cfg.user.username;
  hostname = cfg.host.hostname;
  userNamespaceMigrationSource = pkgs.writeText "wahrwelt-user-namespace-migration.py" (
    builtins.readFile ./user-namespace-migration.py
  );
  migrationTool = pkgs.writeShellApplication {
    name = "wahrwelt-brand-migration";
    runtimeInputs = with pkgs; [
      coreutils
      findutils
      gnugrep
      gnused
      jq
      nix
      rsync
      util-linux
    ];
    text = ''
      set -euo pipefail

      destination=${lib.escapeShellArg destination}
      hostname=${lib.escapeShellArg hostname}
      namespace_python=${lib.escapeShellArg "${pkgs.python3}/bin/python3"}
      namespace_helper=${lib.escapeShellArg userNamespaceMigrationSource}
      work_root="''${WAHRWELT_MIGRATION_WORK_ROOT:-/var/lib/wahrwelt/migration}"

      namespace_migration=0
      if "$namespace_python" "$namespace_helper" "needs-migration" "$destination"; then
        namespace_migration=1
      else
        namespace_status=$?
        if [ "$namespace_status" -ne 1 ]; then
          exit "$namespace_status"
        fi
      fi

      legacy_installer_marker=0
      canonical_installer_marker=0
      if [ -f "$destination/flake.nix" ]; then
        if grep -qE '^[[:space:]]*# Generated by MySetup installer\.[[:space:]]*$' "$destination/flake.nix"; then
          legacy_installer_marker=1
        fi
        if grep -qE '^[[:space:]]*# Generated by Wahrwelt installer\.[[:space:]]*$' "$destination/flake.nix"; then
          canonical_installer_marker=1
        fi
      fi

      if [ "$namespace_migration" -eq 0 ] && [ "$legacy_installer_marker" -eq 0 ]; then
        exit 0
      fi

      if [ ! -f "$destination/flake.nix" ]; then
        echo "Wahrwelt migration: $destination/flake.nix is missing" >&2
        exit 1
      fi
      if [ "$legacy_installer_marker" -eq "$canonical_installer_marker" ]; then
        echo "Wahrwelt migration: refusing to rewrite an unrecognized or ambiguous $destination/flake.nix" >&2
        exit 1
      fi

      brand_migration="$legacy_installer_marker"

      validate_work_directory() {
        local path="$1"
        local owner mode resolved

        if [ -L "$path" ] || [ ! -d "$path" ]; then
          echo "Wahrwelt migration ownership collision: $path must be an ordinary directory" >&2
          exit 1
        fi
        resolved="$(realpath -e -- "$path")"
        if [ "$resolved" != "$path" ]; then
          echo "Wahrwelt migration ownership collision: $path must not traverse symlinks" >&2
          exit 1
        fi
        owner="$(stat -c %u -- "$path")"
        mode="$(stat -c %a -- "$path")"
        if [ "$owner" != 0 ] || [ "$((8#$mode & 0022))" -ne 0 ]; then
          echo "Wahrwelt migration ownership collision: $path must be root-owned and not group/world-writable" >&2
          exit 1
        fi
      }

      case "$work_root" in
        /*) ;;
        *)
          echo "Wahrwelt migration ownership collision: work root must be absolute: $work_root" >&2
          exit 1
          ;;
      esac
      normalized_work_root="$(realpath -m -- "$work_root")"
      if [ "$normalized_work_root" = / ] || [ "$normalized_work_root" != "$work_root" ]; then
        echo "Wahrwelt migration ownership collision: unsafe work root: $work_root" >&2
        exit 1
      fi

      trusted_ancestor="$work_root"
      while [ ! -e "$trusted_ancestor" ] && [ ! -L "$trusted_ancestor" ]; do
        next_ancestor="$(dirname -- "$trusted_ancestor")"
        if [ "$next_ancestor" = "$trusted_ancestor" ]; then
          echo "Wahrwelt migration ownership collision: cannot resolve work root: $work_root" >&2
          exit 1
        fi
        trusted_ancestor="$next_ancestor"
      done
      while :; do
        validate_work_directory "$trusted_ancestor"
        [ "$trusted_ancestor" != / ] || break
        trusted_ancestor="$(dirname -- "$trusted_ancestor")"
      done

      umask 077
      mkdir -p -- "$work_root"
      validate_work_directory "$work_root"
      work_root_id="$(stat -c '%d:%i' -- "$work_root")"
      exec 9<"$work_root"
      if [ "$(stat -Lc '%d:%i' -- /proc/self/fd/9)" != "$work_root_id" ]; then
        echo "Wahrwelt migration ownership collision: work root changed while opening: $work_root" >&2
        exit 1
      fi
      flock 9
      work_root_fd="/proc/self/fd/9"

      destination_parent="$(dirname -- "$destination")"
      destination_parent_id="$(stat -c '%d:%i' -- "$destination_parent")"
      exec {destination_parent_fd}<"$destination_parent"
      destination_parent_pinned="/proc/self/fd/$destination_parent_fd"
      if [ "$(stat -Lc '%d:%i' -- "$destination_parent_pinned")" != "$destination_parent_id" ]; then
        echo "Wahrwelt migration ownership collision: destination parent changed while opening: $destination_parent" >&2
        exit 1
      fi

      create_owned_temp() {
        local kind="$1"
        local parent_pinned="$2"
        local prefix="$3"
        local created

        created="$(
          "$namespace_python" "$namespace_helper" \
            "create-owned-temp" "$kind" "$parent_pinned" "$prefix"
        )"
        IFS=$'\t' read -r created_name created_token <<<"$created"
        case "$created_name" in
          "" | . | .. | */*)
            echo "Wahrwelt migration ownership collision: creator returned an invalid name: $created_name" >&2
            exit 1
            ;;
        esac
        case "$created_token" in
          *:*) ;;
          *)
            echo "Wahrwelt migration ownership collision: creator returned an invalid identity: $created_token" >&2
            exit 1
            ;;
        esac
      }

      creation_barrier() {
        local label="$1"
        local name="$2"
        local identity="$3"
        local ready_name="$4"
        local continue_name="$5"
        local ready_fd continue_fd release

        ready_fd="$(printenv "$ready_name" 2>/dev/null || true)"
        continue_fd="$(printenv "$continue_name" 2>/dev/null || true)"
        if [ -z "$ready_fd" ] && [ -z "$continue_fd" ]; then
          return
        fi
        if [ -z "$ready_fd" ] || [ -z "$continue_fd" ]; then
          echo "Wahrwelt migration ownership collision: incomplete $label creation barrier" >&2
          exit 1
        fi
        printf '%s\t%s\t%s\n' "$label" "$name" "$identity" >&"$ready_fd"
        if ! IFS= read -r -N 1 -u "$continue_fd" release || [ "$release" != 1 ]; then
          echo "Wahrwelt migration ownership collision: $label creation barrier was not released" >&2
          exit 1
        fi
      }

      report_created_recovery() {
        local label="$1"
        local parent_pinned="$2"
        local parent_display="$3"
        local name="$4"
        local identity="$5"
        local owner_fd="''${6:-}"
        local retained="" visible_id found

        if [ -n "$owner_fd" ]; then
          retained="$(readlink -- "/proc/self/fd/$owner_fd" 2>/dev/null || true)"
        fi
        if [ -z "$retained" ]; then
          found="$(
            "$namespace_python" "$namespace_helper" \
              "find-owned-temp" "$parent_pinned" "$identity" 2>/dev/null || true
          )"
          if [ -n "$found" ]; then
            retained="$parent_display/$(printf '%s\n' "$found" | head -n 1)"
          fi
        fi
        if [ -n "$retained" ]; then
          echo "Wahrwelt migration $label retained at $retained" >&2
        else
          echo "Wahrwelt migration $label identity $identity has no visible recovery beneath $parent_display" >&2
        fi
        visible_id="$(stat -c '%d:%i' -- "$parent_pinned/$name" 2>/dev/null || true)"
        if [ -n "$visible_id" ] && [ "$visible_id" != "$identity" ]; then
          echo "Wahrwelt migration unknown collision preserved at $parent_display/$name" >&2
        fi
      }

      pin_created_directory() {
        local label="$1"
        local parent_pinned="$2"
        local parent_display="$3"
        local name="$4"
        local identity="$5"
        local output_fd_name="$6"
        local opened_fd visible_id pinned_id

        if ! exec {opened_fd}<"$parent_pinned/$name"; then
          report_created_recovery "$label" "$parent_pinned" "$parent_display" "$name" "$identity"
          return 1
        fi
        visible_id="$(stat -c '%d:%i' -- "$parent_pinned/$name" 2>/dev/null || true)"
        pinned_id="$(stat -Lc '%d:%i' -- "/proc/self/fd/$opened_fd" 2>/dev/null || true)"
        if [ "$visible_id" != "$identity" ] || [ "$pinned_id" != "$identity" ] || [ ! -d "/proc/self/fd/$opened_fd" ]; then
          report_created_recovery "$label" "$parent_pinned" "$parent_display" "$name" "$identity"
          exec {opened_fd}<&-
          return 1
        fi
        printf -v "$output_fd_name" '%s' "$opened_fd"
      }

      pin_created_file() {
        local label="$1"
        local parent_pinned="$2"
        local parent_display="$3"
        local name="$4"
        local identity="$5"
        local output_fd_name="$6"
        local opened_fd visible_id pinned_id

        if ! exec {opened_fd}<>"$parent_pinned/$name"; then
          report_created_recovery "$label" "$parent_pinned" "$parent_display" "$name" "$identity"
          return 1
        fi
        visible_id="$(stat -c '%d:%i' -- "$parent_pinned/$name" 2>/dev/null || true)"
        pinned_id="$(stat -Lc '%d:%i' -- "/proc/self/fd/$opened_fd" 2>/dev/null || true)"
        if [ "$visible_id" != "$identity" ] || [ "$pinned_id" != "$identity" ] || [ ! -f "/proc/self/fd/$opened_fd" ]; then
          report_created_recovery "$label" "$parent_pinned" "$parent_display" "$name" "$identity"
          exec {opened_fd}>&-
          return 1
        fi
        printf -v "$output_fd_name" '%s' "$opened_fd"
      }

      require_visible_created_directory() {
        local label="$1"
        local parent_pinned="$2"
        local parent_display="$3"
        local name="$4"
        local identity="$5"
        local owner_fd="$6"
        local visible_id pinned_id

        visible_id="$(stat -c '%d:%i' -- "$parent_pinned/$name" 2>/dev/null || true)"
        pinned_id="$(stat -Lc '%d:%i' -- "/proc/self/fd/$owner_fd" 2>/dev/null || true)"
        if [ "$visible_id" != "$identity" ] || [ "$pinned_id" != "$identity" ]; then
          report_created_recovery "$label" "$parent_pinned" "$parent_display" "$name" "$identity" "$owner_fd"
          return 1
        fi
      }

      stage_pinned=
      stage_name=
      stage_token=
      stage_fd=
      candidate=
      candidate_pinned=
      candidate_name=
      candidate_token=
      candidate_fd=
      namespace_snapshot=
      namespace_snapshot_name=
      namespace_snapshot_token=
      namespace_snapshot_fd=
      publish_started=0
      cleanup() {
        status=$?
        trap - EXIT
        if [ -n "$stage_token" ]; then
          report_created_recovery \
            "staging directory" "$work_root_fd" "$work_root" \
            "$stage_name" "$stage_token" "$stage_fd"
        fi
        if [ -n "$namespace_snapshot_token" ]; then
          report_created_recovery \
            "namespace snapshot" "$work_root_fd" "$work_root" \
            "$namespace_snapshot_name" "$namespace_snapshot_token" "$namespace_snapshot_fd"
        fi
        if [ -n "$candidate" ] && [ "$status" -eq 0 ] && [ "$publish_started" -eq 1 ]; then
          echo "Wahrwelt migration previous live tree retained at $candidate" >&2
        elif [ -n "$candidate_token" ]; then
          report_created_recovery \
            "recovery candidate" "$destination_parent_pinned" "$destination_parent" \
            "$candidate_name" "$candidate_token" "$candidate_fd"
        fi
        exit "$status"
      }
      trap cleanup EXIT

      create_owned_temp directory "$work_root_fd" staging.
      stage_name="$created_name"
      stage_token="$created_token"
      creation_barrier \
        stage "$stage_name" "$stage_token" \
        WAHRWELT_TEST_MIGRATION_STAGE_CREATED_READY_FD \
        WAHRWELT_TEST_MIGRATION_STAGE_CREATED_CONTINUE_FD
      if ! pin_created_directory \
        "staging directory" "$work_root_fd" "$work_root" \
        "$stage_name" "$stage_token" stage_fd; then
        exit 1
      fi
      stage_pinned="/proc/self/fd/$stage_fd"

      create_owned_temp file "$work_root_fd" namespace.
      namespace_snapshot_name="$created_name"
      namespace_snapshot_token="$created_token"
      creation_barrier \
        snapshot "$namespace_snapshot_name" "$namespace_snapshot_token" \
        WAHRWELT_TEST_MIGRATION_SNAPSHOT_CREATED_READY_FD \
        WAHRWELT_TEST_MIGRATION_SNAPSHOT_CREATED_CONTINUE_FD
      if ! pin_created_file \
        "namespace snapshot" "$work_root_fd" "$work_root" \
        "$namespace_snapshot_name" "$namespace_snapshot_token" namespace_snapshot_fd; then
        exit 1
      fi
      namespace_snapshot="/proc/self/fd/$namespace_snapshot_fd"

      "$namespace_python" "$namespace_helper" "snapshot-live" "$destination" "$namespace_snapshot"
      cp -a "$destination/." "$stage_pinned/"

      if [ "$brand_migration" -eq 1 ]; then
        if [ -e "$stage_pinned/mysetup" ]; then
          if [ -e "$stage_pinned/wahrwelt" ]; then
            echo "Wahrwelt migration conflict: both state directories exist" >&2
            exit 1
          fi
          mv "$stage_pinned/mysetup" "$stage_pinned/wahrwelt"
        fi

        while IFS= read -r -d "" old_path; do
          old_name="$(basename "$old_path")"
          new_name="$(printf '%s' "$old_name" | sed \
            -e 's/MYSETUP/WAHRWELT/g' \
            -e 's/MySetup/Wahrwelt/g' \
            -e 's/mysetup/wahrwelt/g')"
          new_path="$(dirname "$old_path")/$new_name"
          if [ "$old_path" = "$new_path" ]; then
            continue
          fi
          if [ -e "$new_path" ] || [ -L "$new_path" ]; then
            echo "Wahrwelt migration conflict: both $old_path and $new_path exist" >&2
            exit 1
          fi
          mv -- "$old_path" "$new_path"
        done < <(
          find -H "$stage_pinned" -depth \
            -path "$stage_pinned/secrets" -prune -o \
            -iname '*mysetup*' \
            -print0
        )

        while IFS= read -r -d "" file; do
          sed -i \
            -e 's/MYSETUP/WAHRWELT/g' \
            -e 's/MySetup/Wahrwelt/g' \
            -e 's/mysetup/wahrwelt/g' \
            "$file"
        done < <(
          find -H "$stage_pinned" \
            -path "$stage_pinned/secrets" -prune -o \
            -type f \
            ! -name hashed-password.nix \
            \( \
              -name '*.nix' -o \
              -name '*.json' -o \
              -name '*.md' -o \
              -name '*.txt' -o \
              -name '*.lua' -o \
              -name '*.sh' -o \
              -name '*.fish' -o \
              -name '*.js' -o \
              -name flake.lock \
            \) \
            -print0
        )
      fi

      (
        cd "$stage_pinned"
        "$namespace_python" "$namespace_helper" "migrate-stage" .
      )

      jq empty "$stage_pinned/flake.lock"
      (
        cd "$stage_pinned"
        nix flake update wahrwelt --flake path:.
        nix build \
          --no-link \
          --no-write-lock-file \
          "path:.#nixosConfigurations.$hostname.config.system.build.toplevel"
      )

      if ! require_visible_created_directory \
        "staging directory" "$work_root_fd" "$work_root" \
        "$stage_name" "$stage_token" "$stage_fd"; then
        exit 1
      fi

      create_owned_temp \
        directory "$destination_parent_pinned" ".$(basename "$destination").migration."
      candidate_name="$created_name"
      candidate_token="$created_token"
      candidate="$destination_parent/$candidate_name"
      creation_barrier \
        candidate "$candidate_name" "$candidate_token" \
        WAHRWELT_TEST_MIGRATION_CANDIDATE_CREATED_READY_FD \
        WAHRWELT_TEST_MIGRATION_CANDIDATE_CREATED_CONTINUE_FD
      if ! pin_created_directory \
        "recovery candidate" "$destination_parent_pinned" "$destination_parent" \
        "$candidate_name" "$candidate_token" candidate_fd; then
        exit 1
      fi
      candidate_pinned="/proc/self/fd/$candidate_fd"
      if find -H "$candidate_pinned" -mindepth 1 -print -quit | grep -q .; then
        echo "Wahrwelt migration ownership collision: fresh candidate is not empty: $candidate" >&2
        exit 1
      fi
      rsync -aHAX "$stage_pinned/" "$candidate_pinned/"
      (
        cd "$candidate_pinned"
        "$namespace_python" "$namespace_helper" "validate-migrated" .
      )

      if [ "$brand_migration" -eq 1 ]; then
        if find -H "$candidate_pinned" -path "$candidate_pinned/secrets" -prune -o -iname '*mysetup*' -print -quit |
          grep -q .; then
          echo "Wahrwelt migration left a legacy path in the candidate" >&2
          exit 1
        fi
        if grep -RIl \
          --exclude=hashed-password.nix \
          --exclude-dir=secrets \
          --exclude-dir=.git \
          -i 'mysetup' "$candidate_pinned" 2>/dev/null |
          grep -q .; then
          echo "Wahrwelt migration left legacy text in the candidate" >&2
          exit 1
        fi
      fi

      if ! require_visible_created_directory \
        "recovery candidate" "$destination_parent_pinned" "$destination_parent" \
        "$candidate_name" "$candidate_token" "$candidate_fd"; then
        exit 1
      fi
      "$namespace_python" "$namespace_helper" "precommit" \
        "$destination" "$candidate" "$namespace_snapshot"
      if ! require_visible_created_directory \
        "recovery candidate" "$destination_parent_pinned" "$destination_parent" \
        "$candidate_name" "$candidate_token" "$candidate_fd"; then
        exit 1
      fi
      publish_started=1
      "$namespace_python" "$namespace_helper" "publish" "$destination" "$candidate" "$namespace_snapshot"

      echo "Wahrwelt migration completed: $destination"
    '';
  };
in
{
  systemd.services.wahrwelt-brand-migration = {
    description = "Migrate installed configuration to canonical Wahrwelt paths";
    wantedBy = [ "multi-user.target" ];
    before = [ "home-manager-${username}.service" ];
    after = [ "nix-daemon.socket" ];
    wants = [ "nix-daemon.socket" ];
    restartTriggers = [ userNamespaceMigrationSource ];
    unitConfig.RequiresMountsFor = [
      destination
      cfg.user.homeDirectory
    ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${migrationTool}/bin/wahrwelt-brand-migration";
      RemainAfterExit = true;
      TimeoutStartSec = "30m";
    };
  };

  systemd.services."home-manager-${username}" = {
    requires = [ "wahrwelt-brand-migration.service" ];
    after = [ "wahrwelt-brand-migration.service" ];
  };
}
