package dots

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TakuyaYagam1/wahrwelt/Linux/installer/internal/config"
	"github.com/TakuyaYagam1/wahrwelt/Linux/installer/internal/run"
)

func writeHyprLocalConfig(ctx context.Context, runner run.CommandRunner, state config.State, hyprSourceDir, hyprDir string) error {
	if err := writeHyprLocalConfigFiles(state, hyprSourceDir, hyprDir); err != nil {
		if !os.IsPermission(err) || state.User.Username == "" {
			return err
		}
		if repairErr := repairUserWritableTree(ctx, runner, hyprDir, state.User.Username); repairErr != nil {
			return repairErr
		}
		return writeHyprLocalConfigFiles(state, hyprSourceDir, hyprDir)
	}
	return nil
}

func writeHyprLocalConfigFiles(state config.State, hyprSourceDir, hyprDir string) error {
	sourceHyprland := filepath.Join(hyprSourceDir, "hyprland.lua")
	wahrweltHyprland := filepath.Join(hyprDir, "wahrwelt", "hyprland.lua")
	localConfig := filepath.Join(hyprDir, "wahrwelt", "local.lua")

	if err := os.MkdirAll(filepath.Dir(wahrweltHyprland), 0o755); err != nil {
		return err
	}
	if err := prepareWritableConfigFile(wahrweltHyprland); err != nil {
		return err
	}
	if err := copyRegularFile(sourceHyprland, wahrweltHyprland); err != nil {
		return err
	}

	return writeRuntimeConfigFile(localConfig, renderHyprLocalLua(state))
}

func renderHyprLocalLua(state config.State) string {
	var b strings.Builder
	b.WriteString("-- Generated by Wahrwelt installer; machine-local Hyprland overrides.\n")
	for _, monitor := range displayMonitors(state.Display) {
		b.WriteString(renderLuaMonitor(monitor))
	}
	fmt.Fprintf(&b, "hl.config({\n    input = {\n        kb_layout = %s,\n        kb_options = %s,\n    },\n})\n",
		luaString(state.Locale.KeyboardLayouts),
		luaString(state.Locale.KeyboardToggle),
	)
	return b.String()
}

func displayMonitors(display config.Display) []config.Monitor {
	monitors := make([]config.Monitor, 0, 1+len(display.ExtraMonitors))
	monitors = append(monitors, config.Monitor{
		Name:     display.MonitorName,
		Mode:     display.MonitorMode,
		Position: display.MonitorPosition,
		Scale:    display.MonitorScale,
	})
	monitors = append(monitors, display.ExtraMonitors...)
	return monitors
}

func renderLuaMonitor(monitor config.Monitor) string {
	mode := strings.TrimSpace(monitor.Mode)
	if mode == "" {
		mode = "preferred"
	}
	auto := mode == "preferred" || mode == "auto" || mode == "highres" || mode == "highrr"
	output := monitor.Name
	position := monitor.Position
	if auto {
		output = ""
		position = "auto"
	}
	return fmt.Sprintf("hl.monitor({ output = %s, mode = %s, position = %s, scale = %s })\n",
		luaString(output),
		luaString(mode),
		luaString(position),
		luaString(monitor.Scale),
	)
}

func luaString(value string) string {
	data, err := json.Marshal(value)
	if err != nil {
		return `""`
	}
	return string(data)
}

func writeRuntimeConfigFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := prepareWritableConfigFile(path); err != nil {
		return err
	}
	return atomicWriteFile(path, []byte(content), 0o644)
}

func atomicWriteFile(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	file, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmp := file.Name()
	cleanup := true
	defer func() {
		if cleanup {
			_ = os.Remove(tmp)
		}
	}()

	if _, err := file.Write(data); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Chmod(mode); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		return err
	}
	cleanup = false
	return nil
}

func copyRegularFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0o644)
}

func prepareWritableConfigFile(path string) error {
	info, err := os.Lstat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return os.Remove(path)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("refusing to overwrite non-regular config file: %s", path)
	}
	return nil
}
