package dots

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TakuyaYagam1/wahrwelt/Linux/installer/internal/shellruntime"
)

func writeHyprRuntimeShellState(home, hyprDir string) error {
	profile := shellruntime.BootstrapActiveShell(home, hyprDir)
	statePath := shellruntime.ActiveShellStatePath(home)
	shellLauncher := shellruntime.RuntimeFile(home, "shell-profile.lua")
	shellLauncherBindings := shellruntime.RuntimeFile(home, "shell-launcher.lua")
	shellKeybinds := shellruntime.RuntimeFile(home, "shell-keybinds.lua")
	hyprland := shellruntime.RuntimeFile(home, "hyprland.lua")
	hyprlock := shellruntime.RuntimeFile(home, "hyprlock.conf")
	hypridle := shellruntime.RuntimeFile(home, "hypridle.conf")

	if err := removeLegacyHyprlandRuntimeFiles(home, hyprDir); err != nil {
		return err
	}
	if err := writeRuntimeShellStateFile(statePath, profile); err != nil {
		return err
	}
	if err := writeStableHyprEntrypoints(home, hyprDir); err != nil {
		return err
	}
	if err := writeShellLauncherConfig(shellLauncher, hyprDir); err != nil {
		return err
	}
	if profile != "end4" {
		if err := writeShellLauncherBindingsConfig(shellLauncherBindings, hyprDir, profile); err != nil {
			return err
		}
		return writeLegacyRuntimeShellState(hyprDir, shellKeybinds, hyprland, hyprlock, hypridle, shellLauncher, profile)
	}

	if err := writeEnd4RuntimeShellPlaceholders(shellLauncherBindings, shellKeybinds); err != nil {
		return err
	}
	return writeEnd4RuntimeShellState(hyprDir, hyprland, hyprlock, hypridle)
}

func removeLegacyHyprlandRuntimeFiles(home, hyprDir string) error {
	for _, path := range []string{
		filepath.Join(hyprDir, "hyprland.conf"),
		filepath.Join(hyprDir, "shell-profile.conf"),
		filepath.Join(hyprDir, "shell-launcher.conf"),
		filepath.Join(hyprDir, "shell-keybinds.conf"),
		filepath.Join(hyprDir, "mysetup", "hyprland.conf"),
		shellruntime.RuntimeFile(home, "hyprland.conf"),
		shellruntime.RuntimeFile(home, "shell-profile.conf"),
		shellruntime.RuntimeFile(home, "shell-launcher.conf"),
		shellruntime.RuntimeFile(home, "shell-keybinds.conf"),
	} {
		if err := removeLegacyRuntimeFile(path); err != nil {
			return err
		}
	}
	return nil
}

func removeLegacyRuntimeFile(path string) error {
	info, err := os.Lstat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if info.Mode()&os.ModeSymlink != 0 || info.Mode().IsRegular() {
		return os.Remove(path)
	}
	return fmt.Errorf("refusing to remove non-regular legacy Hyprland runtime file: %s", path)
}

func writeLegacyRuntimeShellState(hyprDir, shellKeybinds, hyprland, hyprlock, hypridle, shellLauncher, profile string) error {
	if err := writeShellKeybindsConfig(shellKeybinds, hyprDir, profile); err != nil {
		return err
	}
	if err := writeMySetupHyprEntrypointConfig(hyprland, shellLauncher, fmt.Sprintf("mysetup (%s)", profile)); err != nil {
		return err
	}
	if err := writeShellManagedRuntimePlaceholder(hyprlock, "Hyprlock", profile, "Caelestia and Noctalia use shell-native lock flows."); err != nil {
		return err
	}
	return writeShellManagedRuntimePlaceholder(hypridle, "Hypridle", profile, "Caelestia and Noctalia use shell-native idle flows.")
}

func writeEnd4RuntimeShellState(hyprDir, hyprland, hyprlock, hypridle string) error {
	if err := writeEnd4HyprEntrypointConfig(hyprland); err != nil {
		return err
	}
	if err := writeRuntimeSourceConfig(hyprlock, filepath.Join(hyprDir, "end4", "hyprlock.conf"), "Active Hyprlock profile: end4"); err != nil {
		return err
	}
	return writeRuntimeSourceConfig(hypridle, filepath.Join(hyprDir, "end4", "hypridle.conf"), "Active Hypridle profile: end4")
}

func writeEnd4RuntimeShellPlaceholders(shellLauncher, shellKeybinds string) error {
	if err := writeRuntimeConfigFile(shellLauncher, "-- Active shell launcher profile: end4\n-- end4 registers launcher bindings from its own Hyprland Lua modules.\n"); err != nil {
		return err
	}
	return writeRuntimeConfigFile(shellKeybinds, "-- Active shell keybind profile: end4\n-- end4 registers keybinds from its own Hyprland Lua modules.\n")
}

func writeRuntimeShellStateFile(path, profile string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := prepareWritableConfigFile(path); err != nil {
		return err
	}
	return atomicWriteFile(path, []byte(profile+"\n"), 0o644)
}

func writeStableHyprEntrypoints(home, hyprDir string) error {
	runtimeDir := shellruntime.RuntimeDir(home)
	for _, name := range shellruntime.RuntimeFiles {
		comment := ""
		if name == "hyprland.lua" {
			comment = "Wahrwelt stable Hyprland entrypoint."
		}
		if err := writeRuntimeConfigFile(
			filepath.Join(hyprDir, name),
			stableRuntimeSourceConfig(filepath.Join(runtimeDir, name), comment),
		); err != nil {
			return err
		}
	}
	return nil
}

func stableRuntimeSourceConfig(target, comment string) string {
	if strings.HasSuffix(target, ".lua") {
		return fmt.Sprintf(`-- Generated by Wahrwelt: stable Hyprland Lua runtime entrypoint
local home = os.getenv("HOME")
if home == nil then
    error("HOME is not set; cannot locate Wahrwelt Hyprland runtime")
end

local config_home = os.getenv("XDG_CONFIG_HOME") or (home .. "/.config")
local hypr_root = config_home .. "/hypr"
package.path = hypr_root .. "/?.lua;" .. hypr_root .. "/?/init.lua;" .. package.path
dofile(%q)
`, target)
	}
	if comment == "" {
		return fmt.Sprintf("source = %s\n", target)
	}
	return fmt.Sprintf("# %s\nsource = %s\n", comment, target)
}

func writeShellLauncherConfig(path, hyprDir string) error {
	script := filepath.Join(hyprDir, "scripts", "start-shell.sh")
	content := fmt.Sprintf(`-- Runtime shell launcher
hl.on("hyprland.start", function()
    hl.exec_cmd(%q)
end)
`, script)
	return writeRuntimeConfigFile(path, content)
}

func writeShellKeybindsConfig(path, hyprDir, profile string) error {
	profilePath := filepath.Join(hyprDir, profile, "keybinds.lua")
	if _, err := os.Stat(profilePath); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("shell keybind profile missing: %s", profilePath)
		}
		return err
	}
	content := fmt.Sprintf("-- Active shell keybind profile: %s\nrequire(%q)\n", profile, profile+".keybinds")
	return writeRuntimeConfigFile(path, content)
}

func writeShellLauncherBindingsConfig(path, hyprDir, profile string) error {
	profilePath := filepath.Join(hyprDir, profile, "launcher.lua")
	if _, err := os.Stat(profilePath); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("shell launcher profile missing: %s", profilePath)
		}
		return err
	}
	content := fmt.Sprintf("-- Active shell launcher profile: %s\nrequire(%q)\n", profile, profile+".launcher")
	return writeRuntimeConfigFile(path, content)
}

func writeMySetupHyprEntrypointConfig(path, shellProfile, label string) error {
	content := fmt.Sprintf(`-- Active Hyprland profile: %s
local home = os.getenv("HOME")
if home == nil then
    error("HOME is not set; cannot locate Wahrwelt Hyprland config")
end

local config_home = os.getenv("XDG_CONFIG_HOME") or (home .. "/.config")
local state_home = os.getenv("XDG_STATE_HOME") or (home .. "/.local/state")
local hypr_root = config_home .. "/hypr"
local runtime_root = state_home .. "/mysetup/hypr-runtime"
package.path = hypr_root .. "/?.lua;" .. hypr_root .. "/?/init.lua;" .. package.path
dofile(hypr_root .. "/mysetup/hyprland.lua")
dofile(%q)
-- runtime_root is kept for parity with shell-profile-sync generated entrypoints.
local _ = runtime_root
`, label, shellProfile)
	return writeRuntimeConfigFile(path, content)
}

func writeEnd4HyprEntrypointConfig(path string) error {
	content := `-- Active Hyprland profile: end4
local home = os.getenv("HOME")
if home == nil then
    error("HOME is not set; cannot locate end4 Hyprland config")
end

local config_home = os.getenv("XDG_CONFIG_HOME") or (home .. "/.config")
local hypr_root = config_home .. "/hypr"
local end4_root = hypr_root .. "/end4"
package.path = end4_root .. "/?.lua;" .. end4_root .. "/?/init.lua;" .. hypr_root .. "/?.lua;" .. hypr_root .. "/?/init.lua;" .. package.path
dofile(end4_root .. "/hyprland.lua")
`
	return writeRuntimeConfigFile(path, content)
}

func writeRuntimeSourceConfig(path, target, label string) error {
	content := fmt.Sprintf("# %s\nsource = %s\n", label, target)
	return writeRuntimeConfigFile(path, content)
}

func writeShellManagedRuntimePlaceholder(path, component, profile, detail string) error {
	content := fmt.Sprintf("# Active %s profile: shell-managed (%s)\n# %s\n", component, profile, detail)
	return writeRuntimeConfigFile(path, content)
}
